### ISSUE TITLE
Support glob patterns in remote sources

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill#1105]

**Comment by magorlick** [comment]
- Glob patterns in GCS and S3 should map to one source table.  This needs to be clear in the interface.  
- If it is impossible and we can't put into one table we need to throw an error.
- We need to be careful about duckDB sampling and assuming types that are mismatched, though the union of these tables is possible and meaningful.
- Multifile ingestion for all sources should work the same way as glob assuming that all of the imported data will land in one source (local file sources with UI, drag and drop currently create separate tables)

**Comment by hamilton** [comment]
There is a bit of risk around how we handle a large volume of data, which is more likely to occur in a glob pattern. @ericpgreen2 to investigate a bit further.

**Comment by magorlick** [comment]
I want to make sure we understand how we will handle large volumes of data and the scope of that additional work before we start work on the glob pattern ingestion.

**Comment by ericpgreen2** [comment]
@AdityaHegde and I think a good solution is to:
- Set a configuration parameter that sets the maximum total size of ingested files. E.g. `RILL_SOURCE_MAX_BYTES`
- Calculate the total size of the provided files (easy to do _before download_ via the cloud SDKs)
- If the total size exceeds `RILL_SOURCE_MAX_BYTES`, reject the request
- Show a friendly error message, something like: "The provided data files exceed X GB. Please limit your selection and try again."

**Comment by magorlick** [comment]
@medriscoll has asked us to remove glob support from Q4 initiatives.
