### ISSUE TITLE
browser drop down menus look jarring on Windows (WSL), should replace with our nice custom dropdowns

### ISSUE THREAD

**Issue by bcolloran** [rilldata/rill#1132]
There are a handful of browser native drop down menus in our app, and they don't look very good on Windows (WSL).

https://user-images.githubusercontent.com/2380975/198413225-ed63c7ac-cf0f-427b-8a9f-fe85fe3ae447.mp4

We have the much nicer looking dropdown components that we use for time selection in the leaderboards and that are styled to match the rest of the app. Those look also look fine on windows -- we should use them rather than native dropdowns throughout the app.

**Comment by magorlick** [comment]
Let's figure out whether we want to recommend this path before we prioritize work to make it look nice.
https://github.com/rilldata/rill-developer/issues/1143
