### ISSUE TITLE
Do discovery on whether we want to support  Windows WSL

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill#1143]
**Issue**
Rill doesn't currently work for Windows users and this might be a good work around if we are up for maintaining the manual checks with each release to validate that it is working correctly.

**Importance**
We want to support as many platforms as possible and Windows is used for 70% of business computers.

**Definition of Done**
Rill works on windows and we have an evergreen plain to check and maintain this install path with each release.

**Comment by magorlick** [comment]
related: https://github.com/rilldata/rill-developer/issues/510

**Comment by magorlick** [comment]
related: https://github.com/rilldata/rill-developer/issues/765

**Comment by magorlick** [comment]
I would like the infra team to investigate and speak to the robustness of this option and their plans for ongoing maintenance and support @nishantmonu51 .  I can help translate this option into our user-facing docs.

**Comment by nishantmonu51** [comment]
Sure, I will check with infra and discuss when we can prioritize it. removed out of 0.14 for now.
