### ISSUE TITLE
In each source form, move the “source name” field to the bottom of each form

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#1147]
And use a distinctive styling to separate it from the other fields.

**Comment by magorlick** [comment]
Is this part of the work to automatically detect the source name from the file name?

**Comment by ericpgreen2** [comment]
No, I think those should be two separate issues. And I think we should wait until the glob patterns PR is finished before doing  the name detection – because glob patterns are going to change the logic a little bit.
