### ISSUE TITLE
[stub] Models nav menu tool tip has click to open - Sources and Dashboard do not

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill#1155]
![Image](https://user-images.githubusercontent.com/5587788/184549456-b122de25-1239-4f5f-afb8-dc6443a251e7.png)

![Image](https://user-images.githubusercontent.com/5587788/184549426-b3888299-4272-463a-8039-bebe2dccc489.png)

![Image](https://user-images.githubusercontent.com/5587788/184549443-032b225f-f15e-4990-963c-9e823b6ac8db.png)

**Comment by hamilton** [comment]
I would be in favor of removing this "click to navigate" tooltip entirely. It's usually pretty self-explanatory that clicking does something.

**Comment by magorlick** [comment]
I agree let’s remove it
