### ISSUE TITLE
CLI data ingestion commands do not present the overlay in the UI

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill#1165]
**Describe the bug**
Users are unclear on what is happening in the UI when they import files using the CLI because there is no feedback until after the data is imported.

**Importance**
We want users to have a clear understanding of what the state of the application and import is at every step of the way.

**Ask**
Present the overlay in the application with feedback about what is happening during data ingestion with the CLI.

**Comment by hamilton** [comment]
We'll have to rethink this particular bit of functionality, but we should discuss w/ platform how we should handle this case before assigning. cc @begelundmuller

**Comment by begelundmuller** [comment]
This was fixed with async reconcile
