### ISSUE TITLE
The application does not reactively pick up new assets when they are reimported in place

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill#1166]
**Describe the bug**
When a user re-ingests a local fine in place by dropping and replacing, the application is not reactively aware of this change and will continue to surface error messages based on the LAST state of the source or model asset. The only way to restore functionality is to refresh everything or to go through each asset and nudge assests with small edits to pick up the changes.

**Importance**
Surfacing errors that are not actionable or are stale is confusing.

**Ask**
Reactively detect changes in assets and propagate those changes to connected assets at the time of the in place change.

**Comment by AdityaHegde** [comment]
Could not reproduce this when deleting a source of a model and reimporting it in UI. Same with replace the source in the UI.

Only seem to happen when done through CLI for me.
