### ISSUE TITLE
Platform meta

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill#1173]
Moved all tracked issues to project board

**Comment by egor-ryashin** [comment]
as I learned, [protoc-gen-validate](https://github.com/bufbuild/protoc-gen-validate) doesn't support Javascript

**Comment by begelundmuller** [comment]
> as I learned, [protoc-gen-validate](https://github.com/bufbuild/protoc-gen-validate) doesn't support Javascript

Yeah, but we don't need it on the client side – it's only needed to validate request parameters on the server.

**Comment by antimpatel** [comment]
@begelundmuller I am new to this repo, and after going through the tasks to understand more about this project in depth. 
I feel `split runtime. proto in multiple modules` is a good first issue to understand more about the project. 
can I pick the item and go ahead?

**Comment by begelundmuller** [comment]
Hey @antimpatel, thank you for your interest in contributing – and sorry that I missed your comment. The proto refactor impacts a number of outstanding PRs, so it's something we'd prefer to do on the team. If you're still interested in contributing, I would suggest https://github.com/rilldata/rill-developer/issues/1265 as a good first issue :)
