### ISSUE TITLE
Very long dashboard titles push the dashboard CTA off screen on metrics config and dashboard, and can cause weird wrapping in buttons

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill#1183]
![Image](https://user-images.githubusercontent.com/5587788/199752477-993d1d8c-3874-4eb0-a2af-75a02bee1cda.png)

**Comment by bcolloran** [comment]
Adding a bit of detail here: 
- this happens in both the metrics definition and in the dashboard 
- in the dashboard, addition to pushing the button off the screen when the screen is very narrow, medium screen width can also cause the text inside the button on the dashboard wrap. see the additional screenshot below:
![image](https://user-images.githubusercontent.com/2380975/203174847-4fb89d7a-de6e-437a-abf1-7e5e9ca62a07.png)

**Comment by begelundmuller** [comment]
Closing since the metrics editor has been disabled
