### ISSUE TITLE
Notify the user when a new version is available

### ISSUE THREAD

**Issue by AdityaHegde** [rilldata/rill#1213]
We need to notify the user about a new version available.

@magorlick Do we need something in the UI as well? Because with the new auto open of the app not sure how much time a user would spend in the terminal.

**Comment by magorlick** [comment]
Yes, we should have something in the application too. This will need some design thinking but it is critical to make sure our users are getting the latest features so they can come along for the ride.

**Comment by mindspank** [comment]
CLI now notifies on new releases. Let's pick up UI notifications within a separate context
