### ISSUE TITLE
Fix Linux build error for DuckDB 0.6.1

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill#1445]
Upgrading to DuckDB 0.6.1 in https://github.com/rilldata/rill-developer/pull/1438 caused Linux builds to fail, so we reverted to DuckDB 0.6.0 in https://github.com/rilldata/rill-developer/pull/1442.

Here are the build errors we got: https://github.com/rilldata/rill-developer/actions/runs/3691803710/jobs/6250128616

Some observations:
- These look like linker errors to me – maybe we're linking to a wrong version of the `c++` standard library on Linux?
- This is probably a problem in the setup in `go-duckdb`, not in `rill-developer`
- The linking is configured in go-duckdb here: https://github.com/marcboeker/go-duckdb/blob/master/cgo_static.go
  - The notable line is: `#cgo linux,amd64 LDFLAGS: -lstdc++ -lm -ldl -L${SRCDIR}/deps/linux_amd64`
- You can also look at https://github.com/duckdb/duckdb/compare/v0.6.0...v0.6.1 to see what might have changed in DuckDB from v0.6.0 (which compiles) to v0.6.1 (which doesn’t compile on Linux)

**Comment by begelundmuller** [comment]
Some more observations here:

- The static library builds of DuckDB are built using `ubuntu-latest` on Linux. Between v0.6.0 and v0.6.1, that runner was upgraded from Ubuntu 20.04.5 to Ubuntu 22.04.01
- Similar bugs have been reported in `go-duckdb` repo here:
  - https://github.com/marcboeker/go-duckdb/issues/54
  - https://github.com/marcboeker/go-duckdb/issues/58

Maybe the problem is that libc++ is not getting statically linked into the static libraries built in `go-duckdb`. Maybe this could be solved by making the static library built [here](https://github.com/marcboeker/go-duckdb/blob/72b078cd343c9eb3b457b279ab00838fd8ac3ce3/Makefile#L40) fully static?

**Comment by rakeshsharma14317** [comment]
Tried with all the possible ways of fully static linking, Looks like some issues with latest ubuntu GHC.
Option which recommended is to downgraded to 20.04 version.
Ref: 
- [https://github.com/actions/runner-images/issues/6689](https://github.com/actions/runner-images/issues/6689)
- [https://github.com/agda/agda/issues/6384](https://github.com/agda/agda/issues/6384)

**Comment by mindspank** [comment]
Stale
