### ISSUE TITLE
getting erroneous "this aggregation expression is empty" warning in metrics editor

### ISSUE THREAD

**Issue by bcolloran** [rilldata/rill#1451]
Seeing the warning  "this aggregation expression is empty" even though my sum expression (a) is not empty and even (b) references a valid column.

steps I took
- load the csv data at this gist https://gist.github.com/bcolloran/6b48288e076e6b541dd2aeeb9f83214c
- create a new model and enter the sql in that gist
- enter the metrics definitions as shown in the screenshot below (the covered expression is `count(QUANTITYORDERED)/ count(distinct ORDERNUMBER)`)

![image](https://user-images.githubusercontent.com/2380975/207722193-2a6dfb9f-6772-47f2-bf5e-ac9f90cabf3e.png)

**Comment by bcolloran** [comment]
I just tried deleting those rows and refreshing (a few times actually), and somehow it works now.  ????

**Comment by begelundmuller** [comment]
Closing since the metrics editor has been deprecated
