### ISSUE TITLE
Runtime: Script for performance benchmarking

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill#1530]
[Here](https://github.com/rilldata/rill-developer/blob/0be292168eb9b12e640e0f14495be450c12f4d7b/examples/spending/benchmark.go) is a script that runs profiling queries for the [`spending.parquet`](https://github.com/rilldata/rill-developer/blob/0be292168eb9b12e640e0f14495be450c12f4d7b/examples/spending/sources/spending.yaml) dataset. The requests were recorded using the browser and exported, so they  directly map to the requests made during profiling.

We want to make the script generic so it's easy to benchmark profiling performance on a dataset in the future.

- [ ] Make the script generic by having it accept a model name as argument. To get the model's columns, make a catalog lookup request. Put the script in `scripts/run_profiling.go`.
- [ ] Add a benchmark in `runtime/runtime_test.go` (using Go's native benchmarking capability) that creates a project containing the `spending.parquet` dataset and runs all the profiling queries against it (don't use the script above, run tests directly in the benchmark). 
- [ ] Document these new performance measuring capabilities in `runtime/README.md`

**Comment by begelundmuller** [comment]
Closed since the use case is now addressed by the K6 performance script

**Comment by ericokuma** [comment]
📄 [PRD Link](https://www.notion.so/clean-up-tooltips-1d0ba33c8f578005a9dfc1e5ccf29792)
