### ISSUE TITLE
CASTing dates in an invalid way generates no errors in Rill

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill#1570]
**Describe the bug**
`CAST`ing dates in an invalid way generates no errors in Rill.  I don't always see it, but I do with this date format.  I am also struggling to transform this string to a date in Rill generally and get no feedback for `STRPTIME` and `DATE_TRUNC`.

**To Reproduce**
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/5587788/210811108-1161d29f-572b-4470-a9cb-c7a8d4c34e7a.png">

**Expected behavior**
I want to see this error message to help me understand what is going on in Rill
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/5587788/210811707-658b96b2-fc0a-47a7-9969-290e32ee01e4.png">

**Comment by rakeshsharma14317** [comment]
@hamilton I can see that we are receiving the error msg in logs 
`{"protocol": "grpc", "grpc.component": "server", "grpc.service": "rill.runtime.v1.RuntimeService", "grpc.method": "ProfileColumns", "grpc.method_type": "unary", "peer.address": "127.0.0.1:50815", "grpc.start_time": "2023-01-18T20:27:12+05:30", "grpc.code": "Unknown", "grpc.error": "Conversion Error: date field value out of range: \"March 29,2022\", expected format is (YYYY-MM-DD)", "grpc.time_ms": "4.211"}`

Also i checked we are getting 400 error with required msg,
E.g  - model created `select cast('March 29, 2022' as date) union all select cast('March 29, 2022' as date);` as cast_date,  
PFA screenshot
<img width="1086" alt="Screenshot 2023-01-18 at 8 32 36 PM" src="https://user-images.githubusercontent.com/10302719/213206076-a0598b95-6316-4e6a-bb84-d4d40f1626a0.png">

Not sure why is not displayed on UI, Can anyone help from Applications side on this?

**Comment by rakeshsharma14317** [comment]
@hamilton After looking into this issue we found that, for cases where we have runtime issues with views, duckdb simply creates the view (without error) and return the error  when evaluated (once we demand their value)
So below are the action items for this 
- We need to show error return from the API as example above (we can see error in logs)
- In UI we should cancel profiling query API returns an error

cc - @begelundmuller @magorlick

**Comment by begelundmuller** [comment]
Just adding some context here. The problem is that models with query runtime errors (like casting an invalid value) are not detected during reconcile because the model is not run when created as a view. Instead, the model will be created successfully, and the runtime error will surface during profiling. 

To address this:
- The frontend should check if `GetTableRows` (`useRuntimeServiceGetTableRows`) returns an error
- If it returns error:
  - The error should be displayed as if it was a model error
  - (Probably) Other profiling queries should be cancelled (or not – they will just return errors)

**Comment by magorlick** [comment]
We have a path forward. This is on the applications side @hamilton will coordinate the work.
