### ISSUE TITLE
Improve UI support for globs

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill#1618]
This relates to [User experience for glob support (Notion)](https://www.notion.so/rilldata/User-experience-for-Glob-Support-bf5e80537a0446fb9e46b22ecc2eb75c). The backend changes are tracked in https://github.com/rilldata/rill-developer/issues/1616. This issue tracks the necessary frontend changes.

This is still awaiting some scoping from @magorlick; the notes here are from lists put together in notion.

Task list:

- [x] Sanitize the `*` in the source name inferred from path
- [x] The info tool tip needs to say we DO support glob patterns
- [ ] Add UI support for local file globs (setting a path instead of uploading a file)
- [ ] Progress and number of files ingested
- [ ] (Pending clarification) Improved error messages that are humanized and surfaced inside the application
- [ ] (Pending clarification) Add input fields for [glob limits](https://github.com/rilldata/rill-developer/pull/1614/files) when creating a source
- [ ] (Pending backend) Add bool input field for `hive_partitioning` config key when creating a source
- [ ] (Pending backend) Add support for `extract` clause in sources (see [proposal](https://www.notion.so/rilldata/Extracting-a-subset-of-data-from-a-source-38a94272671748338f76aded3c6a8ab4))

**Comment by hamilton** [comment]
discussed in platform sync: first 3 bullets could be tackled now, and after backend / clarification bullets are taken care of, we can proceed with the rest.
