### ISSUE TITLE
Process to Install on Windows .

### ISSUE THREAD

**Issue by akash-goel** [rilldata/rill#1639]
Hi Team,

I am trying to install code base on my local ( Windows System )  . it would be helpful if you can please share the steps to install on the Windows.

I am getting below error.

![image](https://user-images.githubusercontent.com/5937612/213557526-d8ff61aa-3719-471a-98d6-2d20d8c2a8ee.png)

Regards,
Akash

**Comment by magorlick** [comment]
Unfortunately we are not currently available on Windows.  I have heard that people are able to get Rill working using WSL, but we do not officially support it.

https://learn.microsoft.com/en-us/windows/wsl/install

**Comment by chengjie0929** [comment]
I think you should make it support windows. Both duckdb and tad support full platforms. For data analytics or business intelligence, the windows platform accounts for seventy percent. Like them, they offer binary versions for each platform. you all the best!

**Comment by chengjie0929** [comment]
> 感谢您@chengjie0929反馈！我希望我们能尽快支持Windows，这是我在内部继续支持的东西。当我们支持窗口时，我们希望确保它是稳定和完全维护的，当我们的小团队准备好进行这项工作时，我们将到达那里。

Thank you for your reply. I hope to hear from you soon. I wish you all the best!

**Comment by chengjie0929** [comment]
> I appreciate your feedback @chengjie0929 ! I would love for us to support windows soon and it is something I continue to champion internally. When we do support windows, we want to make sure it is stable and fully maintained and we will get there when our tiny team is ready for this effort.

Hello, can you tell me about when the windows version of rii will come out? This year or longer? Thank you very much.

**Comment by magorlick** [comment]
> > I appreciate your feedback @chengjie0929 ! I would love for us to support windows soon and it is something I continue to champion internally. When we do support windows, we want to make sure it is stable and fully maintained and we will get there when our tiny team is ready for this effort.
> 
> Hello, can you tell me about when the windows version of rii will come out? This year or longer? Thank you very much.

We do not currently have an anticipated release date for Rill Developer on Windows.

**Comment by chengjie0929** [comment]
I mean do you eventually have a windows version?

**Comment by magorlick** [comment]
Yes, in the future we would like to support windows.

**Comment by chengjie0929** [comment]
Thank you again for your patient response. And I wish you all the best

**Comment by chengjie0929** [comment]
How long before a binary version of rill for windows? I'm afraid I can't afford to wait.

**Comment by mindspank** [comment]
At this point in time we have no plans on supporting Windows for the local development tool. End-users can still explore and use dashboards via Rill Cloud regardless of OS and device.

As a workaround, Rill can run locally inside of WSL on Windows.
Will re-open if our plans on windows support will change.
