### ISSUE TITLE
check for `connection refused` message in frontend to show current server state

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill#1697]
*Issue*
When I kill the server for Rill the UI now looks like it is infinitely loading data.

*Importance* 
We shouldn't be surfacing the overlay with an ingestion modal when we kill the server because it is confusing for our users.

*Ask*
When the server is killed, surface the overlay with the message that the server is no longer available and Rill needs to be restarted.

**Comment by hamilton** [comment]
IIUC we do not have a way to get the server state without a dedicated API that, if no response is received, we know it's not alive. @begelundmuller what do you think?

**Comment by begelundmuller** [comment]
@hamilton If the backend isn't running, all requests will immediately return with a unique error (IIRC, it's "connection refused"), so you should be able to check for that

**Comment by hamilton** [comment]
@begelundmuller got it, thanks!
