### ISSUE TITLE
user could define time-range filters

### ISSUE THREAD

**Issue by ArnaudRo** [rilldata/rill#1736]
I'd like to define time-range filter options predefined and on-the-fly

Predefined: being able to configure a list of personally configured cases =>a yaml file with (last 2|3|6|10|30 minutes|hours|days|weeks|months|years) ?

to replace the hard-coded cases:
case TimeRangeName.LastHour:
      return TimeGrain.OneMinute;
case TimeRangeName.Last6Hours:
      return TimeGrain.OneHour;
case TimeRangeName.LastDay:
      return TimeGrain.OneHour;
    case TimeRangeName.Last2Days:
      return TimeGrain.OneHour;
    case TimeRangeName.Last5Days:
      return TimeGrain.OneHour;
    case TimeRangeName.LastWeek:
      return TimeGrain.OneHour;
    case TimeRangeName.Last2Weeks:
      return TimeGrain.OneDay;
    case TimeRangeName.Last30Days:
      return TimeGrain.OneDay;
    case TimeRangeName.Last60Days:
      return TimeGrain.OneDay;
    case TimeRangeName.AllTime:

Other feature requested: being able to select a time-range while click-drag on time-series graph

**Comment by hamilton** [comment]
Thanks for the issue @ArnaudRo ~ do you have a specific use-case in mind for this?

**Comment by ArnaudRo** [comment]
yep, with the parquet file in this notebook https://observablehq.com/d/14f521dfc99a1da2 => 12millions of observations for ~50 years
