### ISSUE TITLE
Runtime: Support complex types as `MAP` keys

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill#1798]
We have support for basic `MAP` types, but we are not quite there with the nested values.

The following result set cannot be profiled & currently returns an error in the interface:

```
select map([['a', 'b'], ['c', 'd']], [[1.1, 2.2], [3.3, 4.4]]);
```

There are application concerns to fix here as well, but the first step is to get this working.

The top k & tables APIs give the following error:

```
"map key type not supported by driver"
```

A good heuristic here is to make sure every MAP query on [this page](https://duckdb.org/docs/sql/data_types/map.html) works in both the runtime and the application.

---

Task list:

- [ ] Modify `go-duckdb` to use the same behavior as Python for maps as detailed in a comment [here](https://github.com/marcboeker/go-duckdb/pull/74)

**Comment by nishantmonu51** [comment]
@begelundmuller : Can you take a look or reassign ?

**Comment by begelundmuller** [comment]
It supports nested *values*, just not nested *keys*. I.e. these work:
```
SELECT map(['B', 'A'], [[1, 2], [3,4]]);
SELECT map(['B', 'A'], [map([1, 2], [3,4]), map([1, 2], [3,4])]);
```

This is noted it in the maps PR: https://github.com/rilldata/rill-developer/pull/1787. The reason is that Go does not support nested map *keys* (and for that matter, neither does JSON, JavaScript, Python, or most other languages).

To "fix" it we would have to not use maps to represent DuckDB maps. See details here: https://github.com/marcboeker/go-duckdb/pull/74. Let me know if you think that's worth doing.

**Comment by hamilton** [comment]
Adding context here + see the below screenshot for how DuckDB's CLI handles `MAP` representations.

We need to make sure that the return values match the user’s expectation. A strong expectation is that the representations of values look like how they’d look in other DuckDB contexts. When we violate that expectation by having less coverage than them, it drains the reservoir of goodwill. This is especially the case with types where the DuckDB examples on the website don’t work out of the box (which is the case that motivated the GH issue). It reduces confidence in the tool when people don’t see things in the interface that are considered elementary.

With this in mind, I would opt to change the output of MAP to a string type and use the duckdb representation here. It’s definitely less useful than a structured object, but we already can’t support that in the interface as-is. The best we can opt for is to have the representations match what users would see in the CLI, so they can make a reasonable decision about how to change their models.

<img width="1097" alt="Screen Shot 2023-02-22 at 6 21 04 AM" src="https://user-images.githubusercontent.com/95735/220654762-ddecfb9b-fe56-4ed5-8dc2-cd408abaa2a2.png">
