### ISSUE TITLE
address additional invalidations in the Dashboard Store

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill#1992]
Message written by @nishantmonu51 on Slack:

- Create a dashboard, add a filter on a dim, copy the url, remove the dimension on which filter was added. Revisit the URL, the filter is now invalid and should take to the dashboard home page.
- If there are multiple filters on multiple columns, and one of them got removed - do we redirect to home or try to be smart and just ignore the invalid columns and still keep the filter on other columns. I would prefer for always redirecting to default dash for all invalid cases.

**Comment by AdityaHegde** [comment]
@mindspank @nishantmonu51  We go with showing the most correct version of the dashboard right now. i.e. we remove filters for missing dimension or change the selected leaderboard measure if it is missing, but keep everything else the same.

Do we want to change this behaviour? If not we can close it.
