### ISSUE TITLE
Multipe source and model select in the left pane

### ISSUE THREAD

**Issue by kuatroka** [rilldata/rill#1998]
**Is your feature request related to a problem? Please describe.**
No

**Additional context**
It's just a feature suggestion. Not a problem. It'd be good if after having finished working with multiple files, we could select multiple source (with Shift + click) and delete multiple files or models in one go. Currently, I need to select each source file, go to the 3 dots menu and delete it from there.

**Comment by hamilton** [comment]
Agreed, this would be great.
