### ISSUE TITLE
CLI typo

### ISSUE THREAD

**Issue by jkhwu** [rilldata/rill#2017]
**Describe the bug**
Found a little typo! "Deplyment" --> "Deployment"

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="458" alt="Screenshot 2023-03-31 at 11 38 35 AM" src="https://user-images.githubusercontent.com/30886488/229203062-02ce72db-4878-437b-bb48-d1ec1eecc846.png">

**Desktop (please complete the following information):**

**Additional context**

**Comment by mindspank** [comment]
fixed.
