### ISSUE TITLE
Runtime: Add optional `name` field for dashboard YAML measures and dimensions

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill#2084]
We need some kind of stable key for measures and dimensions as we begin to add new features such as showing / hiding these in the dashboard.

@begelundmuller and I discussed a pretty easy solution: add `name`, which we can auto-generate for the user when they bootstrap from an existing model.

We'll incorporate this into the application once it lands.

Existing defs don't strictly need it; but we'll probably suggest to users down the line that it's strongly recommended for application stability. Or, we'll require it and manually update our codev partner dashboards.

**Comment by bcolloran** [comment]
I don't think this issue is closed by pr #2120 -- we definitely still need a key for dimensions, measures is not enough. 

Also, for the use case that drove this requirement -- ability to toggle visibility of measures and dimensions and serialize the keys of the visible measures and dims into the state url -- will #2120 be sufficient? Do we need client side integration as well, perhaps in `dashboard-stores.ts` or somewhere?

**Comment by hamilton** [comment]
@bcolloran correct, the linked PR is not (as far as I understand) complete. @AdityaHegde can you provide more information here? I see `property` but not `name` for the dimension. We will need to add this as well since it's very possible that a user will want to name a dimension but switch columns for that given dimension.

This is a requirement to finish the show / hide measures & dims functionality.

**Comment by bcolloran** [comment]
I think we also need these "name" items (which are really needed for internal use as ids/keys) to
a) be unique (and for the runtime throw an error if they are not)
b) be _required_ for every measure and dimension (and for the runtime to autogenerate them if they are not present)

I could be wrong, but I think that without those properties the "name" key will not be adequate for the intended purpose, which is to robustly save visibility state in URLs

**Comment by hamilton** [comment]
And just a flag that this is considered a pretty high priority item by the commercial team. Would be great to get the needed changes in this next week once the dust has settled on the cloud code freeze.

**Comment by AdityaHegde** [comment]
The changes were released in 0.28
