### ISSUE TITLE
Deployment: add telemetry for browser parts of deployment

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill#2149]
As of this filing, we don't have the browser parts of the telemetry push for the cloud deployment. Once those screens are implemented we can add this.

https://www.notion.so/49b2aeca8d324fadab4c9a2cb233e6ac

**Comment by ericpgreen2** [comment]
Additionally, Himadri would like us to add [DataDog RUM](https://docs.datadoghq.com/real_user_monitoring/browser/)

**Comment by AdityaHegde** [comment]
The browser part of deployment will be worked on soon. So we can add telemetry during that.
