### ISSUE TITLE
Profiling histograms crash the application on certain model edits

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#2209]
To reproduce:
1. Write this model
```sql
select 10 as num
where num < 100
```
2. Edit it to
```sql
select 10 as num
where num < 10
```
3. The application breaks with the following console error
![image](https://user-images.githubusercontent.com/14206386/234093317-7a42e2f8-33bf-4bf6-b04d-bb08aa1838bc.png)

**Comment by mindspank** [comment]
Fixed.
