### ISSUE TITLE
For existing dashboards, clicking the "add new measure/dimension" buttons doesn't do anything

### ISSUE THREAD

**Issue by bcolloran** [rilldata/rill#2228]
For existing dashboards, clicking the "add new measure/dimension" buttons doesn't do anything, and an error is reported in the console. (When I create a new dashboard it works fine)

https://user-images.githubusercontent.com/2380975/234380541-aa97db7c-5af8-4257-8fdf-02d8bcf3da6a.mp4

@AdityaHegde  I wonder if this is related to the recent work on entity keys?

Here's the top of the console error.
```
Uncaught TypeError: other is undefined
    set name-utils.ts:14
    getName name-utils.ts:14
    addNewMeasure metrics-internal-store.ts:183
    handleCreateMeasure MetricsWorkspace.svelte:123
    create_fragment MetricsEntityTable.svelte:33
    bubble index.mjs:1104
    bubble index.mjs:1104
...
```

**Comment by AdityaHegde** [comment]
This screen is no longer present.
