### ISSUE TITLE
attempting to navigate to the dashboard when a definition has an empty measure or mention immediately returns you to the metrics editor

### ISSUE THREAD

**Issue by bcolloran** [rilldata/rill#2232]
**Describe the bug**
attempting to navigate to the dashboard when a definition has an empty measure or mention immediately returns you to the metrics editor

https://user-images.githubusercontent.com/2380975/234407928-1138a78b-e54f-4142-833a-bddb52e5efc5.mp4

**To Reproduce**
1. navigate from a working dashboard to the metrics editor
2. add a new measure or dimension to the definition, but leave it blank
3. attempts to go back to the dashboard

**Expected behavior**
navigating to the dashboard should work even if blank measures or dimensions are present in the metrics definition. Any blank entry should simply be ignored

**Comment by mindspank** [comment]
Not valid for the new editor anymore
