### ISSUE TITLE
Show / Hide Dims & Measures – create a "no measures / dims selected" placeholder

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill#2266]
This is a follow on for #2034.

We need a simple placeholder for both measures and dimensions:
- measures – I expect the x axis to disappear and to have something that just says "no measures visible"
- dimensions – I expect just a "no dimension visible" placeholder
- in both cases, we should probably use the same placeholder.

**Comment by mindspank** [comment]
Duplicates https://github.com/rilldata/rill/issues/3834
