### ISSUE TITLE
Make sure measure and dimension visibility state is synced in urls

### ISSUE THREAD

**Issue by bcolloran** [rilldata/rill#2267]
Spoke to @hamilton today and we have decided to go ahead merge the visibility toggle menus for measures and dimensions in https://github.com/rilldata/rill-developer/pull/2034. 

Following up from that, we will still need to make sure that this visibility state is robustly shareable in URLS

Related to the work started by @begelundmuller  and @AdityaHegde here: https://github.com/rilldata/rill-developer/pull/2120, and related to this issue https://github.com/rilldata/rill-developer/issues/2084, we need
1) to make sure that the solution for #2084 is completed, and that we have keys for measures and dimensions
2) to make sure that these names/keys are always unique and always present, see https://github.com/rilldata/rill-developer/issues/2084#issuecomment-1526379837

Once that is done, and once those keys are available in the store code, it should be a simple matter to swap out the measure expression and filtering dimension for these stable keys

Per converation with @hamilton , assigning to @AdityaHegde  to follow up on this

**Comment by AdityaHegde** [comment]
This change was done in one of the releases. We use `name` everywhere now.
