### ISSUE TITLE
Request: JSON field support?

### ISSUE THREAD

**Issue by swyxio** [rilldata/rill#2295]
**Is your feature request related to a problem? Please describe.**
i have a "metadata" field that is always a JSON object of misc stuff:

![image](https://user-images.githubusercontent.com/6764957/235540944-ea7c8ba1-d1ee-4bc5-bc38-e4bae81690e5.png)

i'd love to facet by those fields since that's how my database (chromadb) stores metadata

**Describe the solution you'd like**
simple json support/smooshing into nullable fields

**Comment by ericpgreen2** [comment]
Cleaning up some old GitHub issues, and apologies that nobody responded to this! The recommended approach would be to handle this in the modeling layer. In your `chroma_embeddings_model.sql` file, you could explode your JSON blob into individual fields.
