### ISSUE TITLE
currency: is it possible to choose something other than USD?

### ISSUE THREAD

**Issue by aborruso** [rilldata/rill#2394]
Thank you

![image](https://user-images.githubusercontent.com/30607/233774662-dafe7316-74d2-444d-8900-8f957f81a305.png)

_Originally posted by @aborruso in https://github.com/rilldata/rill-developer/discussions/2198_

**Comment by mindspank** [comment]
Long overdue but dashboard files support d3-format strings now that would allow you to specify formats for other currencies.

https://docs.rilldata.com/reference/project-files/dashboards

**Comment by aborruso** [comment]
Really great, thank you very much @mindspank
