### ISSUE TITLE
Infra: Rename `rill-developer` repo to `rill`

### ISSUE THREAD

**Issue by nishantmonu51** [rilldata/rill#2443]
We already publish packages as `rill`

**Comment by nishantmonu51** [comment]
@himadrisingh : Can you help take this one ? 
Few things to verify - 
1. Git history, issues remains intact
2. Able to redirect users from current git URL to new one 
3. Release publishing works fine after deployment 
4. Github actions for tests etc, do not break

**Comment by himadrisingh** [comment]
1. Git history remains
2. Git takes care of the redirection
3. Will need few changes thr to make it work with new naming convention
4. GA should work, might require some minor changes
5. Github Apps should work as they don't depend on `rill-developer` repo

**Comment by begelundmuller** [comment]
This is now completed
