### ISSUE TITLE
Dashboard breaks if you edit metrics while time range is Last 6 Hours

### ISSUE THREAD

**Issue by skokenes** [rilldata/rill#2448]
**Describe the bug**
If you open a dashboard, set the time range to Last 6 Hours, open the Metrics Config, and then press "Go to Dashboard", the dashboard does not load.

https://github.com/rilldata/rill-developer/assets/5554373/d574832e-7ca7-4106-a284-06511cd549c6

**To Reproduce**
1. Open a dashboard
2. Select Last 6 Hours for time range
3. Click Edit Metrics
4. Click Go to Dashboard

**Comment by skokenes** [comment]
Also seems to be broken if you have All Time but choose hourly grain. This includes the example project. See longer video here

https://github.com/rilldata/rill-developer/assets/5554373/c4a71b90-bb40-4cc6-97e3-038e6ac9f829

**Comment by mindspank** [comment]
Stale and fixed somewhere along the lines
