### ISSUE TITLE
When changing a model column name, the profiling requests for that column uses the old column name

### ISSUE THREAD

**Issue by AdityaHegde** [rilldata/rill#2662]
We are sending multiple calls for both old and new column name. This is because we invalidate the column profile call at the same time as other profiling calls during modelling. The old query with old column name is refetched and once column profile completes the new query with new column name is fetched. We need to add `enabled` to all profiling calls and make sure they run after column profile completes.

**Comment by ericpgreen2** [comment]
One idea is, when the column name changes, use [`queryClient.removeQueries()`](https://tanstack.com/query/v4/docs/react/reference/QueryClient#queryclientremovequeries) rather than `queryClient.invalidateQueries()` to prevent a refetch of the old column name
