### ISSUE TITLE
Runtime: Fix bug in query result pagination on Druid

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill#2680]
In a `MetricsViewRows` API call using a limit of `10000`, we got this error:

```
An error was encountered while processing your request: QueryInterruptedException: Druid can only fetch forward. Requested offset of 0 != current offset 5,000 -> IAE: Druid can only fetch forward. Requested offset of 0 != current offset 5,000
```

It appears that pagination does not currently work for the Druid driver?

**Comment by egor-ryashin** [comment]
This fails if for example OFFSET 100, OFFSET 10 requests are issued in that order. Druid doesn't support that.

**Comment by egor-ryashin** [comment]
Looks like Avatica-Go mismanages the result set offset.

**Comment by egor-ryashin** [comment]
Fix https://github.com/apache/calcite-avatica-go/pull/71
