### ISSUE TITLE
Refactor App State Patterns

### ISSUE THREAD

**Issue by skokenes** [rilldata/rill#2703]
**Initiative**
Refactor our application state patterns to a more consistent and standardized format that will allow us to write more maintainable and extendable business model code.

**Checklist of Issues**
To be updated by the assignee.
- [x] Setup BusinessModelContext and Provider that components can read from for the Dashboard feature (@skokenes, https://github.com/rilldata/rill/pull/2704)
- [ ] At Dashboard feature level, create some directory structure for storing actions and selectors (@skokenes, https://github.com/rilldata/rill/pull/2749)
- [ ] Sub-feature by sub-feature, pull out applicable actions/selectors into their own unit-testable files
- [ ] Existing dashboard store methods to be extracted out into unit-testable functions in directory from item 2?
- [ ] Move dashboard initialization into a top of feature method; don't load dashboard UI until store is initialized (@AdityaHegde )

**Comment by mindspank** [comment]
Outdated - closing.
