### ISSUE TITLE
Runtime: Implement file watching

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill#2730]
For async reconcile, we need the ability to watch for for file changes on disk. The capability should be implemented on `drivers.RepoStore` (only for the `drivers/file` driver) and exposed over a streaming gRPC API. 

Proposed API spec:

```proto
service RuntimeService {
  // WatchFiles streams repo file update events. It is not supported on all backends.
  rpc WatchFiles(WatchFilesRequest) returns (stream WatchFilesResponse) {
    option (google.api.http) = {
      get: "/v1/instances/{instance_id}/files/watch"
    };
  }
}

// FileEvent describes a file change.
enum FileEvent {
  FILE_EVENT_UNSPECIFIED = 0;
  FILE_EVENT_WRITE = 1;
  FILE_EVENT_DELETE = 2;
  FILE_EVENT_RENAME = 3;
}

// Request message for RuntimeService.WatchFiles
message WatchFilesRequest {
  string instance_id = 1 [(validate.rules).string = {pattern: "^[_\\-a-zA-Z0-9]+$"}];
  bool replay = 2;
}

// Response message for RuntimeService.WatchFiles
message WatchFilesResponse {
  FileEvent event = 1;
  string path = 2;
}
```

For the file watching logic, consider using https://github.com/fsnotify/fsnotify (potentially override it to use https://github.com/fsnotify/fsevents on macOS instead).

**Comment by egor-ryashin** [comment]
Could you elaborate `replay`?

**Comment by begelundmuller** [comment]
> Could you elaborate `replay`?

If `replay` is true, it should emit `WRITE` events for all the existing files at the start of the request

**Comment by begelundmuller** [comment]
Closed by https://github.com/rilldata/rill/pull/2753
