### ISSUE TITLE
Add ability to sort Dimension tables by bottom/least values

### ISSUE THREAD

**Issue by cohenscottr** [rilldata/rill#2784]
**Is your feature request related to a problem? Please describe.**
Often, a use case demands looking at the bottom values of a list (what's decreased the most) vs. the top values

**Describe the solution you'd like**
In addition to ability to sort top values (desc) add ability to sort asc (from lowest value)

<img width="262" alt="image" src="https://github.com/rilldata/rill/assets/82397988/9395c3eb-5479-4f35-a8e2-9891e8a37d54">

**Describe alternatives you've considered**
No other option available

**Additional context**
Sorting could be applied at the dashboard level or within a given dimension table once expanded

**Comment by mindspank** [comment]
Expanded dimension table allows users to sort metrics either descending or ascending
