### ISSUE TITLE
Table cells of `INTERVAL` type do not show exact data

### ISSUE THREAD

**Issue by spren9er** [rilldata/rill#2844]
**Describe the bug**

Table cells do not show exact data for `INTERVAL` columns.
Only months and days are shown.
However, correct (full) interval info is used in SQL.

**To Reproduce**

1. Create a small parquet file with an `INTERVAL` column, e.g. in _DuckDB_

    ```sql
    COPY (SELECT INTERVAL '3 years 11 months 16 days 02:11:53' AS interval)
    TO 'types.parquet' (FORMAT PARQUET);
    ```
2. Import parquet file into _rill developer_ as table `types` and run SQL:

    ```sql
    SELECT interval
    FROM types
    WHERE interval > INTERVAL '47 months 16 days 1 hour'
    ```

It shows a result set of one single entry (which is correct), but table cell does not display hours, minutes and seconds.

This is confusing! If data shown in table cell had been used, data entry would have been filtered out.

**Expected behavior**

Shown `INTERVAL` data should be displayed exact.
In above case: Hours, minutes and seconds should be added.

**Screenshots**

<img width="579" alt="Bildschirmfoto 2023-07-31 um 15 45 02" src="https://github.com/rilldata/rill/assets/5602551/678d44b8-7fe5-496e-a8ac-29bce160bd5f">

**Desktop**
 - OS: macOS Ventura 13.4.1
 - Browser: Chrome, Safari

**Comment by magorlick** [comment]
Thank you for reporting @spren9er , I can see how this would be confusing!  We are talking internally about when we might take on this work.

**Comment by bcolloran** [comment]
@begelundmuller -- I'm looking into this, and it seems that interval objects are passed to the client as objects of the form
`{ days: 185, micros: 2556000000, months: 0 }`.

Do we do any conversion to get the data into this form from duckDB? Or does this e.g. represent the internal storage format that duckDB uses, which we pass back to the client in raw form? If we are doing any kind of conversion, what would it take to make sure the client gets back the original form specified without conversion, so that we can recover a string like '3 years 11 months 16 days 02:11:53'?

**Comment by begelundmuller** [comment]
@bcolloran It is directly passing DuckDB's internal format: https://github.com/duckdb/duckdb/blob/20ad35b3faaca0bfbc519dab19601c0bb6a10e23/src/include/duckdb.h#L171

We can map it to another representation if you would prefer – let me know if you have a suggestion.

Just FYI, @egor-ryashin also looked into adding support for `INTERVAL` measure types and found that aggregations on them are not supported yet, see: https://github.com/rilldata/rill/issues/2851

**Comment by bcolloran** [comment]
@spren9er -- we've updated the table representation of intervals to encode duckdb's internal representation losslessly, so e.g. `{ days: 185, micros: 2556000000, months: 3 }` will be rendered as `3mon 185d 2556000000us`, and by holding shift and clicking on the cell, the duckdb interval expression `INTERVAL '3mon 185d 2556000000us'` will be added to your clipboard. 

This of course is unlikely to be the exact string you entered in your original expression, but it will allow you to do things like the `WHERE` filter you attempted in your example above without ambiguity.
