### ISSUE TITLE
Runtime: Investigate BigQuery performance

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill#2847]

**Comment by k-anshul** [comment]
I loaded same data (1 million rows, 41 columns) in both `bigquery` and `gcs`(in form of zipped csv)  and found following observations:

**GCS connector** 
---
total time: 5.2s
duckdb ingest time: 4.7s
download time: 0.38s

**BigQuery connector**
---
total time: 65s
time taken for bigquery query job completion: 3.5s (this varied basis results are cached or not from ~4s to ~18s) 
total duckdb ingest time: 22.5s
total data to fetch row and convert results: 37.15s

On analysing the traces it seems most of time is being spent in following operations which is also expected:
1. Converting results from arrow format to go types.
2. Aggregating results and dumping data to disk. 

One point of concern is conversion of `big.Rat` types to string using `rat.FloatString`. It is taking enormous amount of time given there are about 20 `BigNumeric` columns in this data. When I cast these to float64 in query, the query time reduces to  25 seconds where most of the savings are in arrow to go type conversion.
We can suggest this workaround to users having too many `BigNumeric` or `Numeric` columns.
