### ISSUE TITLE
Rill Developer does not detect new JSON files

### ISSUE THREAD

**Issue by kmatt** [rilldata/rill#2907]
**Describe the bug**

When a data source is path with a wildcard to JSON data files, on project start files are imported on hydration, but when new files are added to the path, they are not auto-imported nor imported on restarting `rill`

**To Reproduce**
1. Data source defined as `/path/to/files_*.json`
2. Initial `rill start $PROJECT`
3. Observe `INFO    Ingesting source "scores" from "/path/to/files_*.json"`
4. Add new JSON data files to path
5. No ingestion messages logged, "Imported on" in Rill UI does not update
6. Stop and restart `rill start $PROJECT`
7. No ingestion messages logged, "Imported on" in Rill UI does not update

**Expected behavior**
New data imported and shown in dashboard

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.2
 - Browser: Chrome 115.0.5790.171
 - Version: rill version 0.31.0 (build commit: 973c4532 date: 2023-08-02T14:48:05Z)

**Comment by begelundmuller** [comment]
Hi @kmatt, the application isn't currently smart enough to detect changed underlying data sources, so it will only re-ingest automatically if the actual source definition has changed.

But if you go to a source's page in the UI, there's a button to manually trigger a source refresh:

<img width="420" alt="Screenshot 2023-08-11 at 18 29 03" src="https://github.com/rilldata/rill/assets/791356/b5d943e2-6d18-4a51-bca7-293987e7a2e2">

Let me know if this works for you

**Comment by kmatt** [comment]
@begelundmuller that opens a file dialog instead of scanning the source folder for new files. In the event that Rill is running on a remote host / VM, or WSL2 when on Windows, the dialog does not reference filesystem local to the `rill` executable.

Ideally it would update or re-import from the data source definitions. In this case there are > 5,000 JSON files, which Rill imports quickly on the new project launch, but UX not great for updates.

**Comment by kmatt** [comment]
> it will only re-ingest automatically if the actual source definition (YAML) has changed.

If YAML references wildcard paths, and they don't need to change when new files appear in data source path, is there a way to force a rehydration?

**Comment by begelundmuller** [comment]
Thanks, the file dialog for a glob pattern is definitely not intended. We'll get that fixed.

As for forcing a rehydration, you can stop Rill and delete the stage.db file it creates in your project directory. That will force it to rehydrate next time it starts.

**Comment by ericpgreen2** [comment]
Hey @kmatt, in Rill's last release (`0.32.0`) we iterated on the Source YAML & UX, and it should fix your problem.

First, define your source like:
```yaml
type: duckdb
sql: select * from read_json('path/to/files*.json')
```
Here are the [DuckDB docs for JSON loading](https://duckdb.org/docs/data/json/overview.html), which you can use to refine your SQL expression.

Second, whenever you add a new file to your directory, on your Source page, click "Refresh Source" and the source will be re-ingested completely.

Mind trying that workflow and seeing if it works for you?

**Comment by kmatt** [comment]
> type: duckdb

Is a definite improvement. Being able to refresh sources from a dashboard page would be nice, but not having to drop the staging DB and restart `rill` is great.

**Comment by ericpgreen2** [comment]
Great to hear. Have you tried publishing your dashboard to Rill Cloud yet? For Rill Cloud, if you're interested in a scheduled refresh (on a cronjob), we can set one up for you behind-the-scenes.

**Comment by kmatt** [comment]
@ericpgreen2  I have "small data" in this project, monitoring a data pipeline for "today's" activity only. Cloud / Druid would be overkill, but so is Tableau which is being used today. A local instance of Rill Developer is perfect.

We do have "Rill Cloud" / Enterprise size projects, but the example this ticket references is not one of them.
