### ISSUE TITLE
Add Arch Linux User Repository (AUR) publication

### ISSUE THREAD

**Issue by artemklevtsov** [rilldata/rill#2911]
Hi,

It would be nice to see rill-bin package in the AUR. GoReleaser already support AUR publication: https://goreleaser.com/customization/aur/

Regards

**Comment by nishantmonu51** [comment]
@artemklevtsov Thanks for the feature request!
In the short term, we are focusing our efforts on supporting the curl-based installation path, but we're totally open to contributions. If you want to jump in and help, that'd be awesome!
