### ISSUE TITLE
CLI: Support pagination on list commands

### ISSUE THREAD

**Issue by rakeshsharma14317** [rilldata/rill#2922]
We already support pagination for `rill sudo user search %%`
We should add it to all CLI commands that list things or return unbounded results for now.
 `rill user/project/org list` CLI commands can return upto first 1000 rows by default and paginate if there are more rows than that.

quick fix in this release - it can be just increasing the page size to 100 and allowing user to pass a `--limit` to increase the page size upto 10K.

**Comment by begelundmuller** [comment]
Instead of `--limit`, we should use the `--page-size` and `--page-token` terminology already present in the `rill sudo` commands
