### ISSUE TITLE
Add --reset Flag to rill start for a Fresh Project Start

### ISSUE THREAD

**Issue by nishantmonu51** [rilldata/rill#2959]
**Feature Request**:
Introduce a `--reset` flag option to the rill start command, allowing users to initiate a clean start for their project.

**Expected Behavior**:
When running `rill start --reset`, the application should:

- Delete any local stage.db if it exists.
- Start the project as if it's the first time, without any previous data state.
- previously created artifacts would still remain intact

**Rationale**:
This feature would be particularly useful for those who want to ensure that they are working from a clean slate without any residual or old data affecting their current project. It streamlines the process, making it easier to reset the project state without manually removing files or performing other cleanup actions.

**Comment by kmatt** [comment]
#2907
