### ISSUE TITLE
Runtime: Investigate changing `column` to `expression` for dashboard dimensions

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill#3009]
- [ ] Investigate if we can support arbitrary dimension expressions
- [ ] Change the YAML field `column` for dimensions to `expression` (keep backwards compatibility)
- [ ] If `expression` is not set, it should default to the dimension `name` (this is the same behavior as DBT)
- [ ] Update metrics APIs to alias dimension columns to the dimension `name` (oversight in earlier PRs)
- [ ] Update the frontend to always use the `dimension` name instead of `column`

**Comment by nishantmonu51** [comment]
Note: This is also needed to support dimensional lookup when serving dashboards on top of druid.
