### ISSUE TITLE
windows release

### ISSUE THREAD

**Issue by gedw99** [rilldata/rill#3104]
would be nice for us poor windows users to have a release for windows.

https://github.com/marcboeker/go-duckdb seems to be the blocker

https://github.com/marcboeker/go-duckdb/issues/115 is the tracking issue

**Comment by mindspank** [comment]
While a windows release would have been nice we currently to do not have the bandwidth to prioritize it at this point.
I would recommend running Rill inside of WSL2 as a temporary workaround until we are ready to re-open it.

**Comment by gedw99** [comment]
I already did it.
