### ISSUE TITLE
Runtime: Change `IngestionLimitBytes` to `StorageLimitBytes` and make it a DuckDB-specific parameter

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill#3130]
Also move the DB size polling into the DuckDB driver instead of having it in the source reconciler

**Comment by k-anshul** [comment]
> Also move the DB size polling into the DuckDB driver instead of having it in the source reconciler

Here is how I plan to handle it ?
1. In the transporters optimistic checks can be added such as if glob pattern says we need to download 80GB and we have limit on 20GB we can exit without downloading any data.
2. The logic of polling db size and checking against the driver config will reside in the duckDB crud APIs. This should handle model materialisation as well (assuming we want to handle them).

**Comment by begelundmuller** [comment]
That sounds good!
