### ISSUE TITLE
Headers of exported dimension table should be measure `label` (if present) not measure `name`

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#3177]

**Comment by begelundmuller** [comment]
Added details in [Notion](https://www.notion.so/rilldata/PRDs-a1fa12e88b994e5e9a63c879deda6189?p=74bf6beca72f4d84af788384813828e7&pm=s)

**Comment by egor-ryashin** [comment]
Here https://github.com/rilldata/rill/pull/3348
