### ISSUE TITLE
Ability to expand columns in dimension leaderboards to see the full text

### ISSUE THREAD

**Issue by cohenscottr** [rilldata/rill#3198]
**Is your feature request related to a problem? Please describe.**
Some dimension names contain long/large strings that get cut off on display. When drilling into the leaderboard, users would like the ability to expand the column width to see more of the text of the dimension name.

**Describe the solution you'd like**
Ability to expand dimension tables - specifically in the leaderboard drilldown (vs. Explore)

**Describe alternatives you've considered**
Tooltips are helpful but only one dimension at a time

**Comment by ericpgreen2** [comment]
Closed by #3213
