### ISSUE TITLE
Bigquery : Allow extracting results more than 10GB in size

### ISSUE THREAD

**Issue by k-anshul** [rilldata/rill#3201]
Currently we pass the SQL query to bigquery SDK. The SDK stores results in a temporary table and uses arrow streams to read the results. Due to [limitation](https://cloud.google.com/knowledge/kb/bigquery-response-too-large-to-return-consider-setting-allowlargeresults-to-true-in-your-job-configuration-000004266) on temporary table this approach will fail if the query retrieves results greater than 10GB in size.
Two approaches can be evaluated to support retrieving large results:
1. The SDK also supports specifying a destination table. We can allow user to specify a destination table in case they expect results to be more than 10GB. We can also evaluate creating this destination table ourselves but that will require wider permissions from the user.
2. Alternatively we can also allow user to directly specify the table from which to extract data and we can directly use the storage API instead of running any query. This is more limited in use case and is only helpful if user is running `select * from project.dataset.table` query but is going to be lot more efficient since the first approach will just copy everything to the destination table.

**Comment by k-anshul** [comment]
An alternate approach that we we have discussed in past is to follow an approach similar to athena and ask user for a gcs directory where can extract query results. But this will also require wider permissions similar to approach 1. If we decide to go with approach 1 I think this approach can be evaluated since it saves us from copying the data to temporary local parquet files.

**Comment by k-anshul** [comment]
> We can also evaluate creating this destination table ourselves but that will require wider permissions from the user.

Need to evaluate but I think we may already be having this permission since we create temporary table as well. But another issue could be related to managing the state of these tables. Table expiration can only be set at a dataset level.

**Comment by begelundmuller** [comment]
I think option 2 sounds like a nice and simple solution for now. It saves us from needing wider permissions or getting into table life-cycle management.

**Comment by begelundmuller** [comment]
Will be closed by https://github.com/rilldata/rill/pull/3279
