### ISSUE TITLE
Add a "Select all" button to the dimension detail table when searching for values

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#3248]

**Comment by djbarnwal** [comment]
@ericpgreen2 @jkhwu  Where do you think the `Select all` button should be ?

**Comment by nishantmonu51** [comment]
Details here - https://www.notion.so/Select-all-shortcut-1e20bcd2e2514ab5bdcd7b500a965909

**Comment by ericpgreen2** [comment]
Closed by #3364
