### ISSUE TITLE
Admin: Add support for health checks on `rill admin worker`

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill#3298]
The command `rill admin worker` starts the admin worker process without an admin server. This has the unintended side effect that no health checks are served for the worker, causing k8s to send it into a crash loop.

This isn't trivially easy to solve since the worker may be started alongside the server as well, so it can't just open a port and serve a health check endpoint. We should find a clean way to serve a health check endpoint when only a worker is started.

**Comment by pjain1** [comment]
can we create a new deployment for standalone worker and check if the pid is up for the worker process or do we need something more complex ?

**Comment by begelundmuller** [comment]
Closed by https://github.com/rilldata/rill/pull/3759
