### ISSUE TITLE
Runtime: Support external catalog and external DuckDB table storage on local

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill#3341]
Notes:

- Use a gitignored sub-directory instead, like `./tmp` or `./state` or `./cache`
- Put the DuckDB data in a `data.db` file (unless external table storage is enabled)
- Put the catalog in a sqlite DB inside the sub-directory (name ideas: `meta.db`, `manifest.db`)
- Consider keeping the registry in-memory on local
- Backwards compatibility for `stage.db`

**Comment by k-anshul** [comment]
closed by #3319
