### ISSUE TITLE
Add `strictNullChecks` to `tsconfig.json` everywhere

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#3373]

**Comment by bcolloran** [comment]
currently, we have tsconfig files that set `"strictNullChecks": false` in the following directories:

- [ ] /home/bc/rill/rill-developer/web-admin/src/features/
- [ ] /home/bc/rill/rill-developer/web-admin/src/routes/
- [ ] /home/bc/rill/rill-developer/web-common/src/features/models/
- [ ] /home/bc/rill/rill-developer/web-common/src/features/sources/

Going forward, we'll want to remove those tsconfig files, push the `"strictNullChecks": false`  farther and farther down into subdirectories.

(I'll try to keep this updated, but remember that you can always do a full project text search for `"strictNullChecks": false` to see where these configs are currently set)

**Comment by bcolloran** [comment]
Reassigning to you to finish up `web-admin` @ericpgreen2 . Carry the torch for me! :-)
