### ISSUE TITLE
Add examples to d3 formatting docs

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#3386]
At least a couple examples to include:
- how to format a non-USD currency
- how to specify a certain number of decimal points

**Comment by bcolloran** [comment]
Update on this: to specify a non-USD format, d3-format expects a locale -- you cannot do it directly. Fixed point formatting is easy enough, so I'll add that for now until product has triaged the need for locale handling.

**Comment by ericpgreen2** [comment]
Ah that's too bad re: currencies. At least the one example for fixed point formatting would help clarify whether users are supposed to provide e.g. `d3.format(".2f")` or just `".2f"`.
