### ISSUE TITLE
Catch application runtime bugs in an error boundary and record stacktraces in telemetry

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#3387]
For capturing runtime errors:
- Svelte does not have a native error boundary. See: https://github.com/sveltejs/rfcs/pull/46.
- The oft-cited third-party Svelte library is the [Crown Framework](https://github.com/CrownFramework/svelte-error-boundary), but it is unmaintained.
- Hooking into `window.onerror` and `window.onunhandledrejection` seems like one valid option.
```js
window.onerror = (msg, url, line, col, error) => {
    // capture error & emit telemetry
    // show a full error page
};
window.onunhandledrejection = (event) => {
    // capture error & emit telemetry
    // show a full error page
};
```
- Sentry implies their [Svelte SDK](https://docs.sentry.io/platforms/javascript/guides/svelte/) captures runtime errors

For recording stacktraces in telemetry:
- Let's use Sentry
- Ideally we proxy the requests through our backend

**Comment by AdityaHegde** [comment]
Done as part of #3478 3516

**Comment by ericpgreen2** [comment]
Re-opening because we still need to do this for Rill Developer.

**Comment by ericpgreen2** [comment]
Notes for the second pass:
- Telemetry for Rill Developer (as mentioned above)
- Can we capture more information for the "unknown error" case? It's happening frequently.
- Capture the environment: `dev` vs `test` vs `stage` vs `prod`

**Comment by AdityaHegde** [comment]
There were some challenges to get this working locally and not have a lot of spam. Especially when actively modelling there are a lot of errors for the resource API when the model is not valid.
