### ISSUE TITLE
Dashboard hangs where source has auto refresh set

### ISSUE THREAD

**Issue by zom-bee** [rilldata/rill#3388]
**Describe the bug**
There is a UI error (as shown in the screenshot) when there are multiple sources and Model has a join query between multiple of those sources.

**To Reproduce**
1. Setup multiple sources pointing to local parquet.
2. Setup source definition to include auto refresh at `every` 5m
3. Observe Dashboard generating error in console and hang. 

**Expected behavior**
Dashboard should swiftly refresh. Also provide an option to start and end source auto refresh. Also, dashboard should auto recover from any backend error by retrying. 

**Screenshots**
![Screenshot 2023-11-05 at 8 27 47 PM](https://github.com/rilldata/rill/assets/13501485/4e95ff0f-678c-4f39-a62f-994e257ee99c)

**Desktop (please complete the following information):**
 - OS: OS X Sonoma
 - Browser : Chrome
 - Version : 118

**Additional context**
Workaround : Manual refresh of the browser fixes the issue.

**Comment by nishantmonu51** [comment]
@zom-bee. Thanks for reporting the issue. Ideally there should be no downtime during a refresh. 
@AdityaHegde : Can you help look into it.
