### ISSUE TITLE
Go to Dashboard from model shows `undefined` in pop-over

### ISSUE THREAD

**Issue by thomasneirynck** [rilldata/rill#3389]
**Describe the bug**

Selecting `Go to Dashboard` from the model-page, will show `undefined` rather than the Dashboard name

**To Reproduce**
1. Create a model
2. Create one or more dashboards from this model
3. Select the model
4. Click `Go to Dashboard` in the top right
5. The pop-up shows `undefined` for each Dashboard
6. Clicking on of these will link to a broken Url : `http://myhost/dashboard/undefined`

**Expected behavior**

The popover shows the dashboards by name. Clicking one of them goes to the correct dashboard.

**Screenshots**

<img width="363" alt="image" src="https://github.com/rilldata/rill/assets/1833023/3c3735d3-b3c7-4b7b-97ff-bd649cb5f215">

**Desktop (please complete the following information):**
 - OS: iOs
 - Browser: Chrome

**Additional context**
Using rill version `0.36.7 – c13ed366`

**Comment by nishantmonu51** [comment]
@thomasneirynck : Thanks for the bug report. I am able to reproduce the same behavior. We will update with a fix asap.

**Comment by ericpgreen2** [comment]
@thomasneirynck, thanks for the report! We've merged a fix that will be included in our release next week.

**Comment by thomasneirynck** [comment]
thank you @ericpgreen2 and @nishantmonu51 !
