### ISSUE TITLE
Runtime: Fix `received message larger than max` bug

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill#3401]
As reported in the bug bash:

> 1. (Egor) `grpc: received message larger than max (27645481 vs. 4194304)` for timeseries DAY time grain  `{"measureNames":["total_records"],"filter":{"include":[{"name":"ship_region","in":["Lara"]}],"exclude":[]},"timeStart":"1996-07-02T00:00:00.000Z","timeEnd":"1996-08-02T00:00:00.000Z","timeGranularity":"TIME_GRAIN_DAY","timeZone":"Etc/UTC"}` - [`https://ui.rilldata.io/rilldata/rill-dash-northwind/transformation_dashboard`](https://ui.rilldata.io/rilldata/rill-dash-northwind/transformation_dashboard)

And discussed in [this Notion comment thread](https://www.notion.so/Bug-Bash-Rill-GA-6867ccc289494508ae5f8d966d8902c5?d=ab2399adf75841bd92037cbf01bcad34&pvs=4#7bf537a511784a0895258932e4e9dcb5).

**Comment by egor-ryashin** [comment]
This is the same issue https://github.com/rilldata/rill/issues/3357

**Comment by egor-ryashin** [comment]
<img width="898" alt="image" src="https://github.com/rilldata/rill/assets/14215045/a9543312-1ab8-4293-b238-444ffc955ea1">

**Comment by egor-ryashin** [comment]
Fixed here https://github.com/rilldata/rill/pull/3415
