### ISSUE TITLE
Use updated percent-of-total calculation in  TimeDetailedDimension Table

### ISSUE THREAD

**Issue by bcolloran** [rilldata/rill#3421]
follow up to  #3162, and continuing work of #3331, per @djbarnwal's comment here: https://github.com/rilldata/rill/pull/3331#issuecomment-1787366243

**Comment by djbarnwal** [comment]
Is the expectation that the default percentage for the totals is always 100% no matter what filter is applied on other dimensions?  @mindspank  


![image](https://github.com/rilldata/rill/assets/4402679/2cda2361-b94c-49e3-a29d-5c1056f94636)
