### ISSUE TITLE
Setup a new `rill-qa` project on staging for continuous connectors QA

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill#3430]
- Also add credentials and set up corresponding datasets in Athena, BigQuery, etc.
- Cover edge cases, e.g. views in BigQuery

**Comment by esevastyanov** [comment]
An org [rill-qa](https://ui.rilldata.io/rill-qa) with two projects [Athena](https://ui.rilldata.io/rill-qa/Athena) and [BigQuery](https://ui.rilldata.io/rill-qa/BigQuery) are ready

**Comment by esevastyanov** [comment]
Here is a [source repo](https://github.com/rilldata/rill-qa) with two branches `bigquery` and `athena`

**Comment by esevastyanov** [comment]
Athena: databases `rill_qa`, workgroups and input/output buckets starting with `rill-qa-`), tables and views in two regions: `us-east-1` and `us-west-1`
BigQuery: a dataset `rilldata.qa`, a table, a snapshot, a view, and a materialized view
+ service accounts `rill-qa` in aws and gcp

cc @begelundmuller

**Comment by esevastyanov** [comment]
Merged branches into `main`, moved their content to corresponding directories: `athena`, `bigquery`; and recreated projects. cc @k-anshul
