### ISSUE TITLE
Rill deploy reports ingestion errors, when no errors actually occur, for sources present in the /data directory of projects 

### ISSUE THREAD

**Issue by medriscoll** [rilldata/rill#3449]
**Describe the bug**
When running Rill deploy with data sources present in the /data directory of a Rill project, the runtime reports:

`Could not ingest all sources. Rill requires credentials for the following sources:`

**To Reproduce**
1. Add a source from a local file in Rill Developer
2. Commit the project to Github
3. Deploy the project with `rill deploy`
4. See errors in terminal, but no errors reported in Rill Cloud 

**Expected behavior**
No errors should be reported.

**Comment by k-anshul** [comment]
closed by #3436
