### ISSUE TITLE
Setting connectors.postgres.database_url env variable is not being respected

### ISSUE THREAD

**Issue by AndrewRTsao** [rilldata/rill#3450]
**Describe the bug**
Setting the `connectors.postgres.database_url` environment variable does not seem to work at the moment. This applies to both local Rill development and deploying to Rill Cloud:
1. Passing `--env connectors.postgres.database_url=XXX` to `rill start` is not recognized and will result in an error, plus a prompt to do the same thing again (screenshots attached).
2. Using `rill env configure` before `rill deploy` to set `connector.postgres.database_url` doesn't seem to have an effect either.

Issue is reproducible and I can confirm that using the same URI works when testing with `psql`.

**To Reproduce**
1. Create a new Postgres RDS database and load some sample data
2. Make sure to pass in `--env connectors.postgres.database_url=XXX` to `rill start` in Rill developer
3. Create a new source to this Postgres RDS database but don't specify the `database_url` in the YAML
4. Test the connection locally
5. Try to set the same variable in `rill env configure` before deploying
6. Try deploying the project to Rill Cloud

**Expected behavior**
You should be able to connect both locally and using Rill Cloud by passing in this environment variable.

**Actual behavior**
The `connectors.postgres.database_url` env var is not getting picked up and you'll get a connection error.

**Screenshots**
<img width="1360" alt="passing same postgres url to connectors postgres database_url" src="https://github.com/rilldata/rill/assets/45043255/1b5bbee8-cb8c-4bd1-ba41-0a76e41e4075">
<img width="1657" alt="postgres url not working" src="https://github.com/rilldata/rill/assets/45043255/60fe3835-9574-495f-8618-2e9de0c2da78">
<img width="1045" alt="postgres url works with psql" src="https://github.com/rilldata/rill/assets/45043255/a6352bad-8b40-40ba-94be-50ee86c547b6">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser ARC / Chrome
 - Rill Version: 0.36.7

**Comment by k-anshul** [comment]
We moved from `connectors.postgres.database_url` to `connector.postgres.database_url`. The docs and logs wasn't updated unfortunately. 
Fixed the docs and logs here : https://github.com/rilldata/rill/pull/3515
Thanks for reporting.
