### ISSUE TITLE
Adding support enum in postgres

### ISSUE THREAD

**Issue by xqbumu** [rilldata/rill#3530]
**Is your feature request related to a problem? Please describe.**

When there is an enum type in a PostgreSQL table, Rill will prompt that "custom datatypes are not supported", but in reality, PostgreSQL returns data of type uint32.

**Describe the solution you'd like**

We can use the TypeMap feature of pgx to register the corresponding data type.

Additionally, we may also need to register the enum in the oidToMapperMap in Rill.

To determine if the current field is an enum, we need to use the Codec of pgtype.Type.

**Additional context**
Refer:
- https://github.com/jackc/pgx/blob/master/conn.go#L1248

- get current query's fields oids

```go
oids := make([]uint32, 0, 8)
for _, fieldOpt := range rows.FieldDescriptions() {
oids = append(oids, fieldOpt.DataTypeOID)
}
RegisterDataTypesByOID(ctx, conn, oids)
```

- register data for conn

```go
func RegisterDataTypesByOID(ctx context.Context, conn *pgx.Conn, oids []uint32) error {
	var typeName string
	for _, typeOID := range oids {
		err := conn.QueryRow(ctx, "SELECT typname FROM pg_type WHERE oid = $1;", typeOID).Scan(&typeName)
		if err != nil {
			return err
		}
		dataType, err := conn.LoadType(ctx, typeName)
		if err != nil {
			return err
		}
		conn.TypeMap().RegisterType(dataType)
	}

	return nil
}
```

**Comment by mindspank** [comment]
Thanks for a great feature request, we'll see if we can tackle this within our next sprint starting 4th of December
