### ISSUE TITLE
First run fails: connection reset by peer(edited)

### ISSUE THREAD

**Issue by HaveF** [rilldata/rill#3551]
**Describe the bug**
First run fails:
```
curl -s https://cdn.rilldata.com/install.sh | bash
rill start my-rill-project
```

```shell
(base) ╭─mac@iMac ~/Desktop/proj/temp
╰─$ rill start my-rill-project


2023-11-24T20:23:11.641	ERROR	Not parsing changed paths due to broken rill.yaml
2023-11-24T20:23:21.641	ERROR	Not parsing changed paths due to broken rill.yaml
```

**To Reproduce**
1. curl -s https://cdn.rilldata.com/install.sh | bash
2. rill start my-rill-project
3. even I copy rill.yaml from other example project, it still not works(hung over there):
```
╰─$ rill start my-rill-project


2023-11-24T20:28:37.987	INFO	Hydrating project '/Users/mac/Desktop/proj/temp/my-rill-project'
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 12.0.1 (21A559)
```
╰─$ rill --version
rill version 0.37.2 (build commit: f6060729 date: 2023-11-16T19:00:25Z)
```

**Additional context**

**Comment by HaveF** [comment]
Still can't run after install from brew

(base) ╭─mac@iMac ~/Desktop/proj
╰─$ rill --version
rill version 0.38.1 (build commit: ccec0d5e date: 2023-12-20T12:33:15Z)
(base) ╭─mac@iMac ~/Desktop/proj
╰─$ rill start my-rill-project

2023-12-20T21:06:04.202	WARN	Not parsing changed paths due to broken rill.yaml
2023-12-20T21:06:14.203	WARN	Not parsing changed paths due to broken rill.yaml
2023-12-20T21:06:24.202	WARN	Not parsing changed paths due to broken rill.yaml
2023-12-20T21:06:34.203	WARN	Not parsing changed paths due to broken rill.yaml
2023-12-20T21:06:44.200	WARN	Not parsing changed paths due to broken rill.yaml

**Comment by begelundmuller** [comment]
Hey @HaveF, thanks for reporting this issue and my apologies for the late response.

As I see it, the issue is one of redundant warning log messages. I have pushed a PR here to suppress them: https://github.com/rilldata/rill/pull/3805

Until it's released, you can still open the application (on `http://localhost:9009`) and use it, everything should work as expected despite the warning logs.

**Comment by HaveF** [comment]
@begelundmuller Thanks for your reply.
What I meant not works, means, not works on `http://localhost:9009`

![image](https://github.com/rilldata/rill/assets/54462/c3e61fe8-d93d-4166-8731-aee702549685)


Installed again with brew:
```
╰─$ brew install rilldata/tap/rill                                                                                  1 ↵


==> Fetching rilldata/tap/rill
==> Downloading https://cdn.rilldata.com/rill/v0.38.2/rill_darwin_amd64.zip
################################################################################################################# 100.0%
==> Installing rill from rilldata/tap
Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences.

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 14.2.

==> Downloading https://formulae.brew.sh/api/formula.jws.json
################################################################################################################# 100.0%
🍺  /usr/local/Cellar/rill/0.38.2: 5 files, 153.1MB, built in 7 seconds
==> Running `brew cleanup rill`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /Users/mac/Library/Caches/Homebrew/rill--0.38.1.zip... (49.3MB)

╭─mac@iMac ~/Desktop/proj
╰─$ rill start my-rill-project


2024-01-09T22:29:05.996	WARN	Not parsing changed paths due to broken rill.yaml
2024-01-09T22:29:15.994	WARN	Not parsing changed paths due to broken rill.yaml
2024-01-09T22:29:26.056	WARN	Not parsing changed paths due to broken rill.yaml
2024-01-09T22:29:36.056	WARN	Not parsing changed paths due to broken rill.yaml
```

**Comment by begelundmuller** [comment]
@HaveF Ahh, that looks unrelated to the warning logs. I notice now that you're not seeing a log message `Serving Rill on: http://localhost:9009`, which indicates the local server hasn't started yet.

Some questions:
- Do you by any chance have anything running on port 49009 already?
- What output do you get if you navigate to `http://localhost:9009/v1/ping` in the browser while the application is running?

**Comment by HaveF** [comment]
@begelundmuller Thanks for your help!

Very strange! I have tried many times(reinstall and try), but this time works...

I'll check the port next time when I meet the issue again.

```
╭─mac@iMac ~/Desktop/proj
╰─$ sudo lsof -i :49009
╭─mac@iMac ~/Desktop/proj
╰─$ netstat -vanp tcp | grep 49009                                                                                 1 ↵
╭─mac@iMac ~/Desktop/proj
╰─$ rill start my-rill-project                                                                                     1 ↵


2024-01-10T07:40:52.797	WARN	Not parsing changed paths due to broken rill.yaml
2024-01-10T07:40:53.524	INFO	Serving Rill on: http://localhost:9009
2024-01-10T07:41:02.796	WARN	Not parsing changed paths due to broken rill.yaml
2024-01-10T07:41:12.796	WARN	Not parsing changed paths due to broken rill.yaml
```

finally, I see the line `2024-01-10T07:40:53.524	INFO	Serving Rill on: http://localhost:9009`

Btw, the port `49009` you said is something special, or just typo(correct one is `9009`)?

**Comment by HaveF** [comment]
@begelundmuller Aha, I reproduce the issue again!

![image](https://github.com/rilldata/rill/assets/54462/7a72064c-62f4-4517-bb00-1405dd3aa434)

```
╭─mac@iMac ~/Desktop/proj
╰─$ rill start my-rill-project


2024-01-10T07:54:27.671	INFO	Hydrating project '/Users/mac/Desktop/proj/my-rill-project'
2024-01-10T07:54:27.674	INFO	Reconciling resource	{"name": "metrics_margin_monitoring", "kind": "Source"}
2024-01-10T07:54:27.906	INFO	Reconciled resource	{"name": "metrics_margin_monitoring", "kind": "Source", "elapsed": "232ms"}
2024-01-10T07:54:27.906	INFO	Reconciling resource	{"name": "metrics_margin_model", "kind": "Model"}
2024-01-10T07:54:27.917	INFO	Reconciled resource	{"name": "metrics_margin_model", "kind": "Model", "elapsed": "11ms"}
2024-01-10T07:54:27.917	INFO	Reconciling resource	{"name": "customer_margin_dash", "kind": "MetricsView"}
2024-01-10T07:54:27.929	INFO	Reconciled resource	{"name": "customer_margin_dash", "kind": "MetricsView", "elapsed": "11ms"}
```

not find `INFO	Serving Rill on: http://localhost:9009` for a long time.

In another console:
```
╭─mac@iMac ~/Desktop/proj/python_training_mdlz
╰─$ sudo lsof -i :49009
COMMAND  PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
rill    5123  mac   10u  IPv6 0xa1ed37f40e0d342d      0t0  TCP *:49009 (LISTEN)
```


I suspect it is potential related with network. `connection reset by peer` is [a very common error](https://en.wikipedia.org/wiki/Great_Firewall) here.

If `rill` support env 'HTTPS_PROXY', the issue can be resoved.

**Comment by begelundmuller** [comment]
@HaveF Interesting – I have some questions:
- Are you on a corporate network or VPN of some kind? I'm wondering if there's something intercepting your `localhost` network traffic.
- What operating system are you on?
- How might a `HTTPS_PROXY` env var help? Rill only connects to `localhost`, it doesn't need to connect to anything outside of your local machine.

**Comment by HaveF** [comment]
@begelundmuller Thanks for still being here to help me out. 

For me, localhost should be no problem? (I haven't had this problem with any of my previous dev tools, etc.)

In theory, rill does not need to connect to the external network, but in fact I noticed that when it started, my firewall prompted (but I forgot what external address was accessed, maybe rilldata.com). 

In addition, in the newly opened page, there are some demos that require access to the external network.

I am using Mac 12.0.1, and the firewall is little snitch.

**Comment by begelundmuller** [comment]
@HaveF no problem :)

You're right that Rill connects to the internet in some cases (e.g. for downloading example projects, for some anonymous telemetry, and for managing cloud deployments if you decide to use those features). I should have been clearer – it doesn't need access to the internet, i.e. you should be able to create an empty project and load data even if your internet is disabled.

As for your issue, Rill doesn't use the ports 7890 or 52083. Rill internally makes some requests to itself on localhost, and it looks like their ports might be rewritten and proxied badly, maybe by Little Snitch? If you close it, does Rill work normally then?

**Comment by HaveF** [comment]
@begelundmuller The 0.39.0 version does not seem to have the problems I mentioned above. I will read the rill documentation today and try it out. And I will report back if there are any problems.

In addition to the startup problem, I am wondering if we can abide by some conventions of the environment variable HTTPS_PROXY when downloading the sample project?

**Comment by HaveF** [comment]
@begelundmuller Although I had some difficulties with network access, I finally downloaded the https data source in the demo and changed it to local_file, and I finally entered rill. Many thanks for the help. This problem seems to be normal in 0.39.0.
