### ISSUE TITLE
Rill requires public internet access during boot

### ISSUE THREAD

**Issue by janjagusch** [rilldata/rill#3576]
**Describe the bug**

You cannot start Rill in a work environment without access to the public internet (which is common when working with corporate, sensitive data). That's because Rill tries to install several DuckDB extensions at startup:
https://github.com/rilldata/rill/blob/f4978e78a23ad1c2812053d63cbc907f5128153e/runtime/drivers/duckdb/duckdb.go#L405-L418

**To Reproduce**
1. Disable internet access on your machine
2. Start Rill
3. Try to export a model as parquet

You will get the following error:

```
IO Error: Failed to download extension "json" at URL "http://nightly-extensions.duckdb.org/v0.9.2/linux_amd64/json.duckdb_extension.gz"
Extension "json" is an existing extension.
 (ERROR Connection)
```

**Expected behavior**

I would expect that Rill ships all necessary extensions as part of its binary, instead of installing them during the boot. If that's not possible I would expect that Rill allows me to specify a [custom extension repository](https://duckdb.org/docs/extensions/working_with_extensions.html#using-a-custom-extension-repository).

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Edge
 - Version v0.37.2

**Comment by begelundmuller** [comment]
Hello @janjagusch, the DuckDB `INSTALL` commands should be no-ops if the extensions are already available on your system, so two possible workarounds for you are:

1. Install the DuckDB CLI and use it to run the `INSTALL`s while pointing it to a custom extension repository that you have access to.
2. Do your first run of Rill with access to the public internet. After the first run, the extensions will be installed and Rill should work without internet access.

**Comment by begelundmuller** [comment]
Hey @janjagusch, pending environment variable support from the DuckDB side, another option for you is that we already support injecting custom boot queries using a CLI flag, like this:

```bash
rill start my-project --env connector.duckdb.boot_queries="SET custom_extension_repository='path/to/extensions'"
```

Currently, we run those queries after the extensions are installed, but we'd be happy to move them up to run before extension installation, so that you can use it to override the extension repository.

Let me know if that would help, then I'll make the change (would then be available in the next nightly, and next week's release).

**Comment by begelundmuller** [comment]
Great, made the change in [this PR](https://github.com/rilldata/rill/pull/3589), which should make it into tomorrow's nightly (you can download it with `rill upgrade --nightly`) :)
