### ISSUE TITLE
Comparison menu - Handling for empty strings as label values

### ISSUE THREAD

**Issue by nishantmonu51** [rilldata/rill#3610]
**Describe the bug**
<img width="363" alt="Screenshot 2023-12-04 at 10 13 08 AM" src="https://github.com/rilldata/rill/assets/5023786/04eadc3a-61c6-4c62-8203-f6a878421e6c">

```
 - label: ""
    property: "tags"
    description: ""
```
When label is null or empty string we should to fallback to using the column name as we do in the leaderboards.

**Comment by djbarnwal** [comment]
Fixed at #3556
