### ISSUE TITLE
Support for threshold based measure filters

### ISSUE THREAD

**Issue by nishantmonu51** [rilldata/rill#3618]
https://www.notion.so/rilldata/Measure-Filters-08e7a4d2c52c46b28374aadaf48e8ac0?pvs=4#1d9bcdfea4bf43cd9ee80adcdf960933

**Comment by AdityaHegde** [comment]
PR in review: https://github.com/rilldata/rill/pull/3730

**Comment by nishantmonu51** [comment]
This is merged now.
