### ISSUE TITLE
Deprecate `ListCatalogEntries` in `rill-load-test`

### ISSUE THREAD

**Issue by k-anshul** [rilldata/rill#3643]
This API previously had some latency issues. This is now deprecated so we didn't look at improving its performance as well.
Migrate to `v1/instances/{instance_id}/resources?kind=rill.runtime.v1.MetricsView` API to list the dashboards in `rill-load-test`

**Comment by kaspersjo** [comment]
Updated the API here [here](https://github.com/rilldata/rill-load-test/commit/43bc66cbba211452b560b0fbfc9b1d294577aab2)
