### ISSUE TITLE
Feat: Add Pylon widget to Rill Cloud

### ISSUE THREAD

**Issue by AndrewRTsao** [rilldata/rill#3652]
To provide a better integrated and native support experience, let's add the Pylon in-app chat widget to Rill Cloud (and make it available to _every end user_). Per latest conversation, requirements should be:
- On every Cloud UI page, display the standard Pylon widget.
- For dashboards, we should hide the standard pylon widget and the chat window can only be triggered by navigating to Profile > Ask for help.

Based on talking with the Pylon team, we can leverage their [javascript API](https://docs.usepylon.com/chat/api) to have the in-app chat appear expanded once the help button is pushed. Similarly, if we wanted to hide the collapsed version of the chat, there should be an `onChangeUnreadMessagesCount` handler that we can register a callback with, so we can do things like show the chat only if there is a new message for the customer, etc.

**Comment by AndrewRTsao** [comment]
FYI @mindspank for input on the correct product design

FYI @cohenscottr @ericpgreen2 for awareness

**Comment by mindspank** [comment]
As per the reqs above:

Only applicable for deployed projects in Rill Cloud. Not for local.

For Admin users
- On every Cloud UI page, display the standard pylon widget.

For All users
- For dashboards we would hide the standard pylon widget and instead trigger the chat window on Profile -> Ask for help

**Comment by AndrewRTsao** [comment]
@mindspank Updating this GH issue to reflect our desire to broadly enable Pylon in Rill and you can check the original comment for the proposed approach. Please let me know if we feel comfortable with approaching (alternative would be to not introduce another button but simply replace _Profile > Ask for help_ with Pylon instead of a link to Discord).

**Comment by AndrewRTsao** [comment]
@ericpgreen2 Requirements should be updated to reflect the latest and we should feel free to implement
