### ISSUE TITLE
Leaderboards: long scientific notation overflows to two lines (leaderboard)

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#3715]
[As reported in Slack](https://rilldata.slack.com/archives/C02T907FEUB/p1702643738806219)

<img width="831" alt="image" src="https://github.com/rilldata/rill/assets/14206386/a49a0427-95e5-4be4-8067-6b9437175622">

**Comment by bcolloran** [comment]
this one will be fixed by #3716.

follow up issue https://github.com/rilldata/rill/issues/3717

**Comment by bcolloran** [comment]
follow up work tracked in #3717
