### ISSUE TITLE
Running Rill Frontend behind Proxy doesn't work

### ISSUE THREAD

**Issue by janjagusch** [rilldata/rill#3720]
**Describe the bug**

I'm trying to run Rill behind a proxy, for example `https://mydomain.example/proxy/rill`. However, the frontend doesn't load and I'm greeted with a blank screen instead. Looking at the network requests in the browser, it seems like the Rill frontend tries to retrieve the JS assets from the wrong path. For example, it tries to fetch from `https://mydomain.example/_app/immutable/chunks/singletons.f7c0925f.js`, instead of `https://mydomain.example/proxy/rill/_app/immutable/chunks/singletons.f7c0925f.js`. Somehow, the frontend does not include the `proxy/rill` path section in the request.

**To Reproduce**

I'm hoping that this is a simple frontend issue that can be resolved without a reproducible example. However, I can try to put together a minimal reproducible test case, if necessary.

**Expected behavior**

I would expect that the Rill frontend loads the JS assets from the correct path and displays the frontend corrently, instead of showign a blank screen.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Edge
 - Version: 0.38.0

**Comment by begelundmuller** [comment]
Hello @janjagusch, the Rill web app can't be served from a subpath, it needs to be hosted at the domain root. That goes not just for serving the frontend, but also for the API requests made by the frontend (which are all prefixed with `/v1/...`).

If you try to make Rill work behind a proxy, another thing to be aware of is that it relies heavily on streaming HTTP responses. So make sure you allow long lived HTTP requests (I would say at least 1hr).

**Comment by janjagusch** [comment]
Thanks for getting back to me so quickly, @begelundmuller.

> the Rill web app can't be served from a subpath, it needs to be hosted at the domain root. That goes not just for serving the frontend, but also for the API requests made by the frontend (which are all prefixed with /v1/...).

Is that something you think can be fixed? I want to use Rill in a contrained corporate environment where I have no control over which ports are open. So I have no choice but to serve it behind a proxy.

> If you try to make Rill work behind a proxy, another thing to be aware of is that it relies heavily on streaming HTTP responses. So make sure you allow long lived HTTP requests (I would say at least 1hr).

Thanks for letting me know. I will keep that in mind if we can make the proxy solution work.

**Comment by janjagusch** [comment]
> In general, the local application is not really developed with self-hosting in mind.

Can you elaborate on this? How else would I host it? Or is Rill only meant to be used as an Enterprise SaaS in the cloud?

> I think your best bet is to use a proxy that runs at the domain root.

That unfortunately not an option for us. To give you a bit more context:

- In the environment I work in, only one port is open, which **must** run [Jupyter server](https://github.com/jupyter-server/jupyter_server).
- We use [jupyter-server-proxy](https://github.com/jupyterhub/jupyter-server-proxy) to access other services, like Rill, though the Jupyter server port.

I understand that you cannot cater to every esoteric use case your users encounter. However, in the corporate environments I've seen so far, accessing sensitive data usually means having restricted/no access to the internet, which renders a cloud SaaS version of Rill unusable. To enable such use cases, it will often be necessary to self-host Rill and access it behind a proxy.

**Comment by begelundmuller** [comment]
> Can you elaborate on this? How else would I host it? Or is Rill only meant to be used as an Enterprise SaaS in the cloud?

We currently focus on the local read/write experience on `localhost` (similar to Jupyter) and the managed read-only experience on https://ui.rilldata.com (that you deploy to using `rill deploy`).

Others have successfully deployed the `localhost` experience into a hosted environment, but beyond answering questions and suggesting workarounds, it's not really something we have the bandwidth to support properly at the moment.

Regarding the proxy setup, I understand why your current setup doesn't allow you to set up Rill, but unfortunately I can't currently think of any way around needing to run Rill at the domain root.

**Comment by begelundmuller** [comment]
Closing this issue since Rill needs to run at the domain root and changing that would unfortunately be very complex (for example, gRPC which we use heavily also needs to run at the domain root).
