### ISSUE TITLE
Shift + click to copy doesn't work

### ISSUE THREAD

**Issue by amir20** [rilldata/rill#3740]
**Describe the bug**
Tooltip suggests `shit + click` to copy. But it doesn't. 

**To Reproduce**
1. Hover over some dimension 
2. Shift click
3. Copy doesn't work

Instead there is a javascript error:

```
6.7f23be70.js:23 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'writeText')
    at le (6.7f23be70.js:23:5277)
    at HTMLButtonElement.ee (6.7f23be70.js:23:5577)
    at HTMLButtonElement.l (dashboard_pb.7a1a7cda.js:1:2704)
```

**Expected behavior**
It should copy. And even better, there should be some kind of UI notification that copy worked

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] `0.38.1`

**Additional context**
NA

I did search for this and didn't see any existing issues. Hopefully, I didn't miss it.

**Comment by ericpgreen2** [comment]
Hi Amir, I haven't yet been able to reproduce this. Here's a quick [video of it working for me](https://jam.dev/c/4ca179bf-d109-4680-ab51-da443467238e).

Can you provide more information? Do you get this error for a certain data type? Were you on the same page that I was on, or were you on the single-dimension expanded view?

**Comment by amir20** [comment]
Hi @ericpgreen2, I don't actually see in your video pasting. Maybe I missed it. 

Here is a video on my side: 

https://github.com/rilldata/rill/assets/260667/b2ba9ef4-58a8-481c-b35e-3a4f525e73e3

My dashboard is running on a custom port. I have tested it on two browsers on two different laptops. 

I wonder what else I can provide to help on debugging.  I have been using Rill for about two weeks and it has never worked for me.

**Comment by amir20** [comment]
I tried Firefox, Safari, Chrome and Arc browser. They all do the same thing.

**Comment by ericpgreen2** [comment]
> Hi @ericpgreen2, I don't actually see in your video pasting. Maybe I missed it.

Oh I actually didn't paste in my video – the toast notification indicated that the value copied successfully.

I'm seeing that the [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard) is not available over HTTP, only available over HTTPS. Are you self-hosting Rill Developer and might that be the issue?

**Comment by ericpgreen2** [comment]
If you run `window.isSecureContext` in your browser console, and it says `false`, then we have our reason.

**Comment by amir20** [comment]
`window.isSecureContext` is false.  That would be it. I am self hosting. In Safari, I get the error `Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'navigator.clipboard.writeText')`. 

Perhaps, checking with 

```
navigator.permissions.query({ name: "clipboard-write" }).then((result) => {
  if (result.state === "granted" || result.state === "prompt") {
    /* write to the clipboard now */
  }
});
```

I think the right thing to do would be to disable so the user knows that it is not possible.  

Would be the right thing to do.

**Comment by ericpgreen2** [comment]
Okay, glad we could debug this. It looks like MDN recommends [feature detection](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts#feature_detection) like so:
```js
if (window.isSecureContext) {
  // ...
}
```

Agreed, we should disable this feature under this scenario. Thanks for bringing it to our attention!

**Comment by amir20** [comment]
Hey @ericpgreen2, I am not very efficient with Svelete, but I know Vue really well. With Vue, I use [useClipboard](https://vueuse.org/core/useClipboard/).  Looking at their code, I think the best practice would be to check for the right [permissions](https://github.com/vueuse/vueuse/blob/dd82044a8dc7f2558270bace100c36da20954bf5/packages/core/useClipboard/index.ts#L66-L67). I don't think  `window.isSecureContext` is enough because user could have disabled access to clipboard.

**Comment by ericpgreen2** [comment]
@amir20, we just merged a fix for this (see the PR linked above). The fix will be included in next week's release. Thanks for calling this out!
