### ISSUE TITLE
Make it possible to adjust the height of the "Model Data" dashboard module

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#3744]
In `RowsViewer.svelte`, the height is currently fixed at `h-72`. The height should be dynamic and controlled via dragging the "Model Data" header up/down.

**Comment by kensuke-b-sasaki** [comment]
Hi @ericpgreen2 , I'm k_ssk on discord, thank you for creating issues for new feature.
I really appreciate for your cooperation & looking forward to the future implementation!

**Comment by kensuke-b-sasaki** [comment]
@ericpgreen2 
Today I upgrade to v0.39.0 and confirmed this change is applied.
Really appreciate for your help!

**Comment by ericpgreen2** [comment]
Terrific! Don't hesitate to reach out if there's anything else that would improve your experience.
