### ISSUE TITLE
Improve dimension search behavior

### ISSUE THREAD

**Issue by AndrewRTsao** [rilldata/rill#3839]
We should improve the search behavior so that the search box is cleared out when the end user returns to the All Dimensions view and/or when drilling into a different dimension (to avoid reusing a prior and likely not relevant search context). Would be a nice small QOL improvement to the interactive experience when the user is exploring and interacting with their data. 

More context in Discord [here](https://discord.com/channels/959796421832343562/959801632151969792/1195136905386397896).

**Comment by mindspank** [comment]
Fixed in last release.
