### ISSUE TITLE
Scheduled report: "Open in browser" link in old emails does not use the correct time range

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#3870]
Each email uses the same time range (often a relative time range). Each email should use a fixed time range so the report run is unique.

**Comment by ericpgreen2** [comment]
Update from Benjamin: This is to be fixed in the refactor that accounts for Alerts.

**Comment by begelundmuller** [comment]
Put an implementation suggestion in [this Slack message](https://rilldata.slack.com/archives/C06638A72TH/p1705681083309619)

**Comment by ericpgreen2** [comment]
Closed by https://github.com/rilldata/rill/pull/3894
