### ISSUE TITLE
Support for window functions / rolling averages in dashboard expressions

### ISSUE THREAD

**Issue by AndrewRTsao** [rilldata/rill#3895]
A common request that we see in the field / use case is the ability to support rolling averages or window functions through dashboard expressions, allowing for richer analysis and more dynamic exploration of the data. For example, users may have measures that are a combination of different time granularities and dimensions or want to define rolling metrics to analyze cohorts of data over different segments of time.

**Comment by mindspank** [comment]
Closed via https://github.com/rilldata/rill/pull/4961
Still some outstanding documentation tasks for when we are ready to "officially" release it but closing for now.
