### ISSUE TITLE
Update `<RillLogoSquareNegative>`,  `<RillLogo>`, and any other logo components/usage in the app

### ISSUE THREAD

**Issue by bcolloran** [rilldata/rill#3903]
@ericpgreen2 @AdityaHegde @djbarnwal @briangregoryholmes -- string search on "Logo" and "logo" finds only the components `<RillLogoSquareNegative>` and `<RillLogo>` that need to be updated for brand transition. Are there any other components or usages anywhere in the app?

**Comment by bcolloran** [comment]
fyi @jkhwu

**Comment by jkhwu** [comment]
Browser tab favicon for both Dev and Cloud:

https://www.figma.com/file/rrcVngskc3p6mIIYg1jH8Y/Rill-Visual-Identity?type=design&node-id=612-146232&mode=design&t=qt9F9MbAQwKZCQzj-11

Rill dev welcome page

https://www.figma.com/file/Qt6EyotCBS3V6O31jVhMQ7/RILL?type=design&node-id=1987-35610&mode=design&t=BkgjZVfS7TyqoZIL-11

**Comment by jkhwu** [comment]
All logo variants can be found here: https://www.figma.com/file/rrcVngskc3p6mIIYg1jH8Y/Rill-Visual-Identity?type=design&node-id=257-2583&mode=design&t=qt9F9MbAQwKZCQzj-11

**Comment by bcolloran** [comment]
closed by https://github.com/rilldata/rill/pull/3927
