### ISSUE TITLE
Finer brand color adjustments to dashboard

### ISSUE THREAD

**Issue by jkhwu** [rilldata/rill#3907]
https://www.figma.com/file/Qt6EyotCBS3V6O31jVhMQ7/RILL?type=design&node-id=3224-55814&mode=design&t=2SlPTPxwRkk2Srpl-11

**Note:** When we have time we should go back and make the finer color adjustments shown above, such as the text color for Measure and Dimension labels (I believe this will better prompt users to click them to discover our other surfaces).

Also button colors in the upper right.

**Comment by bcolloran** [comment]
Closing this -- some of the designs have been updated in the last month and some of this has already been implemented. Recommend opening new GH issues to track remaining design work.
