### ISSUE TITLE
Update filter pill colors

### ISSUE THREAD

**Issue by jkhwu** [rilldata/rill#3908]
**Pills**

Related to the rebranding, I’ve updated our pill colors so that dimension pills use our primary color palette and measure pills use our secondary color palette.

https://www.figma.com/file/Qt6EyotCBS3V6O31jVhMQ7/RILL?type=design&node-id=3427-82036&mode=design&t=2SlPTPxwRkk2Srpl-11

**Comment by mindspank** [comment]
Has been adjusted afaik.
