### ISSUE TITLE
Update brand colors on Rill Cloud pages

### ISSUE THREAD

**Issue by jkhwu** [rilldata/rill#3909]
**Login/Signup Pages**

https://www.figma.com/file/Qt6EyotCBS3V6O31jVhMQ7/RILL?type=design&node-id=5131-162648&mode=design&t=2SlPTPxwRkk2Srpl-11

**Link/Text Buttons**

https://www.figma.com/file/nqqazRo1ckU9ooC9ym9weI/Rill-Design-System?type=design&node-id=1156-254709&mode=design&t=Scidzo2gfdWvh1ax-11

![Screenshot 2024-01-24 at 2 02 06 PM](https://github.com/rilldata/rill/assets/30886488/32437c38-7883-43ba-a0aa-cea0a725b503)

**Brand buttons**

https://www.figma.com/file/nqqazRo1ckU9ooC9ym9weI/Rill-Design-System?type=design&node-id=1155-311775&mode=design&t=Scidzo2gfdWvh1ax-11

**Comment by bcolloran** [comment]
will be fixed by #4144. Or at least fixed enough. Should open new issues for additional design changes, i think #4144 gets the high priority stuff
