### ISSUE TITLE
Feat: Restore User State

### ISSUE THREAD

**Issue by mindspank** [rilldata/rill#3932]
We would like to restore user UI state whenever a user comes back to a dashboard.

UI State to restore:
- Measure list (which measures are visible)
- Dimension/Leaderboard list (which dimensions are visible)
- Active Measure and sort order

Only the last state is needed, no need to retain a history of state.

It's not expected for last state to sync across devices but if possible lets go for it.

**Comment by nishantmonu51** [comment]
While we are here lets also get ability to set defaults in dashboard yaml. 
https://www.notion.so/rilldata/Setting-defaults-for-selected-dimensions-measures-a542c3abf325450e896dc411f1167c91

**Comment by AdityaHegde** [comment]
Defaults in dashboard were done in this: #3974
