### ISSUE TITLE
When trying to `rill deploy` when not logged in, link should be shown in case opening browser fails

### ISSUE THREAD

**Issue by bcolloran** [rilldata/rill#3935]
**Describe the bug**

Trying to deploy a project without being logged in, I see the message--
`Please log in or sign up for Rill. Opening browser...`
-- but my browser never opens.

I'm therefore stuck and unable to log in / deploy my project.

If the message just said
```
Please log in or sign up for Rill. Opening browser to
https://rill.blahblahblah....
```
then I'd at least be able to manually copy+paste the url and complete the flow

This is what other similar CLIs do, for example the gcloud cli:
![image](https://github.com/rilldata/rill/assets/2380975/a3c098f2-8aa7-48e6-97af-fd15686d83ca)

**Desktop (please complete the following information):**
 - OS: WSL ubuntu

**Comment by mindspank** [comment]
@bcolloran Do you have a cloud env running locally? Was testing this morning and could observe the same behaviour when trying to deploy on dev locally without a cloud env running.

If you switch to prod via `rill devtool switch-env` you should get a URL back that you can navigate to.
We are suppressing the "server not running" error though, @begelundmuller is producing a fix for local dev
