### ISSUE TITLE
`encodeURIComponent()` is twice called on URL state

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#3955]
There are two instances of URL encoding: 
1. All parameters are URL-encoded in `web-common/src/runtime-client/fetchWrapper.ts`
2. The `state` object is specifically URL-encoded in `web-common/src/features/dashboards/proto-state/dashboard-url-state.ts` 

We should only URL-encode the state object once, not twice.

**Comment by bcolloran** [comment]
I started looking into this, but it's not obvious to me how or whether these two url encoding paths are conflicting or redundant, which one is to be prefered, etc.

The data flow around this stuff is rather complicated and I haven't looked at it before, and breaking it would be bad news, so I think it would be safer and more efficient for @AdityaHegde to audit this than for me to do a deep dive to understand how this works and make a change. I can take this if that really seems like the best path (in which case some more context would be helpful), but for now I'm going to reassign to Aditya.
