### ISSUE TITLE
Cloud UI: show detailed error message on the Error Page

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#3978]
Request from Slack:

When we show a full page error in the cloud UI, could we find a way to show the actual/detailed error message on the error page (could be very small type)? Potentially it could be just for admin users or hidden under a “see error details” pane.

**Comment by jkhwu** [comment]
Screen mock: https://www.figma.com/design/Qt6EyotCBS3V6O31jVhMQ7/RILL?node-id=510-8476&t=zz3ot3x4RTJSWxPL-11
Error details component: https://www.figma.com/design/Qt6EyotCBS3V6O31jVhMQ7/RILL?node-id=13490-564534&t=zz3ot3x4RTJSWxPL-11
Click prototype: https://www.figma.com/proto/Qt6EyotCBS3V6O31jVhMQ7/RILL?page-id=144%3A815&node-id=510-8476&viewport=-14233%2C-15532%2C0.54&t=vyWhf99lcCQiqr1R-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=510%3A8476&show-proto-sidebar=1
