### ISSUE TITLE
TypeErrors in dimension table crash the app

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#3992]
<img width="552" alt="image" src="https://github.com/rilldata/rill/assets/14206386/5e28d74f-9fef-4376-8983-ada5bfc2037e">

<img width="547" alt="image" src="https://github.com/rilldata/rill/assets/14206386/481bc4a1-e271-4f5e-afd7-bc1037ed06c2">

**Comment by bcolloran** [comment]
part of #3679
