### ISSUE TITLE
State management: add Immer to prevent unnecessary derived store updates

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#4022]
Our current state management package suffers from unnecessary derived store updates, which has numerous downstream performance impacts. It's described in "Problem 1" of #3960.

We have a hypothesis that Immer middleware could isolate our derived stores and prevent unnecessary re-renders.

**Comment by AdityaHegde** [comment]
We have a prototype. We are probably not going with the immer approach.
