### ISSUE TITLE
SQL Editor: `tab` pressed at the end of the line should not indent the beginning of the line

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#412]
To reproduce:
- My query is `select * from nyc311_reduced` on a single line
- My cursor is at the end of the line
- I press the tab key
- The beginning of the line indents

Platform: Google Chrome

(updated w/ reproduction steps)

**Comment by magorlick** [comment]
@ericpgreen2 , is this still a problem I am not seeing it anymore.

**Comment by ericpgreen2** [comment]
Yes, I'm still seeing this behavior on `0.13.0`

**Comment by magorlick** [comment]
Can you please provide repro steps? I couldn't reproduce what you are seeing.

**Comment by bcolloran** [comment]
i am able to reproduce this

**Comment by magorlick** [comment]
I can too with these steps. Lets fix it. :)
