### ISSUE TITLE
Ability to cycle between defined time intervals across periods in the UI

### ISSUE THREAD

**Issue by AndrewRTsao** [rilldata/rill#4131]
For a given time interval (e.g last 7 days), end users may want to be able to quickly cycle between different periods of time without having to manually adjust the range each time. For example, if you're looking at the last week, we should provide an easy way to then adjust to the previous week (same range but one period back), two weeks ago, etc. Similarly, if we're looking at a one month period from last year, there should be an easy ability to move forward / back by 30 days from the UI.

More context here:
https://github.com/rilldata/cs-feature-requests/issues/10

**Comment by jkhwu** [comment]
There are some ideas for how to get left/right buttons to appear when hovering over our charts, but I'd propose a quick-win here: enable shortcuts with the left and right arrow keys.
