### ISSUE TITLE
Dashboard: leaderboards at the bottom of the screen are cut off

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#4218]
I'm unable to scroll down to see all the values in the bottom leaderboards. The values are cut off. Looking at the scroll bar (not shown in picture), it appears as if the container is taller than is shown on the screen.

<img width="717" alt="image" src="https://github.com/rilldata/rill/assets/14206386/39691792-6079-47be-9fee-5a8aae375a49">

**Comment by briangregoryholmes** [comment]
Self-assigned. My layout PRs will address this.

**Comment by briangregoryholmes** [comment]
Closed by #4229
