### ISSUE TITLE
Flag missing or Document error

### ISSUE THREAD

**Issue by akshayjain3450** [rilldata/rill#4252]
**Describe the bug**
For a developer, the command to start rill is given as `./rill start --project dev-project`. The issue with this is there is no such flag as project against the start command. Either it is a document error which it seems to be. 

**To Reproduce**
1. Run this command: `./rill start --project dev-project`
(Make sure you have the binary build as per the ReadME in CLI.)

**Expected behavior**
I expected for rill to start from the dev-project location. But instead I get the error as this:
`Error: unknown flag: --project`

**Screenshots**
Current Document
<img width="898" alt="Screenshot 2024-03-06 at 1 08 22 PM" src="https://github.com/rilldata/rill/assets/39643112/ed071df1-c53d-4fc7-b622-3bbdd0010c9d">

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.3.1
 - Browser: Brave Browser
 - Version: Running Github Code

**Additional context**

**Comment by akshayjain3450** [comment]
I have added a PR #4253 for the fix. 
Thank You

**Comment by mindspank** [comment]
Closed via #4253
