### ISSUE TITLE
Feat: Separating metrics views and dashboards

### ISSUE THREAD

**Issue by mindspank** [rilldata/rill#4270]
As Rill grows we want to separate out the metrics layer (view) from the dashboard. Today we mix visual dashboard UI properties with our metrics layer and as we add additional asset types it’s semantically cleaner for them to reference a metric view instead of a dashboard.

In addition a separation of metrics definitions from it’s dependent resources allows us to further promote reusability of the metrics definitions without having to duplicate them.

https://www.notion.so/rilldata/Metrics-Views-as-a-first-class-resource-in-Rill-1a5599f3129547d7ad7151785f4de223?pvs=4

**Comment by nishantmonu51** [comment]
@ericpgreen2 : We should plan this alongwith the File explorer changes.

**Comment by ericpgreen2** [comment]
Closed by https://github.com/rilldata/rill/pull/5724
