### ISSUE TITLE
Context cancelled error when refreshing Snowflake source using keypair authentication

### ISSUE THREAD

**Issue by AndrewRTsao** [rilldata/rill#4276]
**Describe the bug**
When you first create a new source using Snowflake keypair authentication, it will succeed. However, if you return to it after a period of time (e.g. 24h) or refresh it many times, the connection will start erroring out with a `context cancelled` error.

**To Reproduce**
1. Create a new source using the Snowflake connector with keypair authentication specifically
2. Note that the connection should succeed if configured properly
3. Create some models and dashboards on top of the source
4. Return the the source after a period of time and re-open it

**Expected behavior**
The Snowflake source should continue to work and you can continue using it. 

**Actual Behavior**

The Snowflake source will throw a `context cancelled` error. Furthermore, if you create a brand new Snowflake source using the exact same keypair and pointing to the same table, it will succeed.

_Note: Tested with basic auth and everything works correctly_

**Screenshots**

![Snowflake_keypair(old)](https://github.com/rilldata/rill/assets/45043255/62e48e72-06ba-4707-b8ba-f0c4b3cd6010)
![Snowflake_keypair2(new)](https://github.com/rilldata/rill/assets/45043255/a98fb87f-41db-4f24-81d9-e3dc1835fcbc)

**Comment by esevastyanov** [comment]
[Fixed](https://github.com/rilldata/rill/pull/4408)
