### ISSUE TITLE
Support non-default schemas in ClickHouse

### ISSUE THREAD

**Issue by wub** [rilldata/rill#4345]
When using ClickHouse, I can't see any tables in the Rill Developer sidebar when using a non-default schema:

`rill start --db-driver clickhouse --db "clickhouse://localhost:9000/foo"`

Presumably because this code hardcodes the schema to `default`:

https://github.com/rilldata/rill/blob/51e3bef08af66706da41e7a604b625d269ce0332/runtime/drivers/clickhouse/information_schema.go#L30

**To Reproduce**
1. Create a new schema in ClickHouse called `foo`
2. Add some tables to the schema
3. Run `rill start --db-driver clickhouse --db "clickhouse://localhost:9000/foo"`
5. There are no tables in the sidebar

**Expected behavior**
I expect to see the tables in the sidebar.

**Desktop:**
 - macOS Sonoma 14.3.1
 - ClickHouse v24.1

**Comment by nishantmonu51** [comment]
@wub : Thanks for the bug-report, 
@k-anshul : Can you please take a look ?

**Comment by k-anshul** [comment]
Hey @wub 

We just did a patch release that includes fix for this bug. Could you please upgrade and check ?
Please let us know in case you still see any issues.
