### ISSUE TITLE
Alerts: use the measure `label` not `name` in the email

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#4352]
The alert email currently uses the measure `name`, not the measure `label`. Example:

<img width="601" alt="image" src="https://github.com/rilldata/rill/assets/14206386/f9e2cf6d-1c68-45db-aa3c-ac406f5d5211">

**Comment by mindspank** [comment]
I would assume this is the same issue we have with exports as well

**Comment by begelundmuller** [comment]
Sorry, hadn't seen this issue – closing in favor of https://github.com/rilldata/rill-private-issues/issues/237
