### ISSUE TITLE
Refresh doesn't work

### ISSUE THREAD

**Issue by msulim0** [rilldata/rill#4369]
**Describe the bug**
Refresh button on right-up corner doesn't work

**To Reproduce**
1. Use JSON as data source
2. Make changes in it.
3. Try to refresh using 'refresh' button

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari
 - Version Sonoma 14.3.1

**Additional context**
But if you try to refresh using '...' that are located near to data on the left pane, it works

**Comment by mindspank** [comment]
Thanks for reporting! We'll try to reproduce and produce a fix asap.

**Comment by msulim0** [comment]
> Been unable to reproduce this issue. When you select "Local file" as connector and choose a file, we take a copy of data file and store it in the `data` directory within your Rill project folder. Is that the file you are editing?

Oh, my bad. I thought rill reads file directly from path I provide. So, if JSON data was changed I should replace the source and then refresh it. Got it.

Sorry for wasting your time and thanks for the job you do!

**Comment by mindspank** [comment]
You could also edit the file in the data directory if you don't want to re-add it every time.
