### ISSUE TITLE
Feat: Document optional arguments in Custom APIs

### ISSUE THREAD

**Issue by mindspank** [rilldata/rill#4370]
We should document optional arguments as part of the Custom API payloads.
This would allow users to build a single API resource that without arguments supplies a non-filtered dataset but with the possibility to filter it further.

Assume a Custom API with metrics sql such as:
```  
SELECT
  device_type,
  AGGREGATE(overall_spend)
FROM bids
{{ if .args.type }} WHERE device_type = '{{ .args.type }}' {{ end }} 
GROUP BY device_type
```
See discussion below for `hasKey` solution

**Comment by pjain1** [comment]
@begelundmuller we have `"missingkey=error"` option for templating engine so we get this error. Wondering if should make this configurable and not use this while resolving api queries ?

**Comment by k-anshul** [comment]
I think this can be done by using `hasKey` function like below :

```
SELECT
	device_type,
	AGGREGATE(overall_spend)
  FROM bids
  {{ if hasKey .args "type" }} WHERE device_type = '{{ .args.type }}' {{ end }} 
  GROUP BY device_type
  ```

**Comment by k-anshul** [comment]
Also if not documented we should also document that we support all functions supported in the `sprig` library apart from OS functions : https://masterminds.github.io/sprig/

**Comment by mindspank** [comment]
We do mention it here: https://docs.rilldata.com/integrate/custom-apis/sql-api#useful-resources
I was just at fault for only checking the go templating docs and not sprig.

We should probably call out some of the more common scenarios such as hasKey, upper, lower, trim etc

**Comment by k-anshul** [comment]
> We should probably call out some of the more common scenarios such as hasKey, upper, lower, trim etc

Yeah makes sense.
