### ISSUE TITLE
Runtime: a pivoted export doesn't support multiple time grains

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#4416]
When adding two time grains to the pivot table, it appears that the parent time grain (day) merely repeats the child time grain (hour).

<img width="1436" alt="image" src="https://github.com/rilldata/rill/assets/14206386/68e8d5d5-a67d-4f48-a707-4d7816f4efa4">

<img width="789" alt="image" src="https://github.com/rilldata/rill/assets/14206386/0ac0a09b-670e-4a9d-b5a3-3568b1c903f1">

**Comment by egor-ryashin** [comment]
aliases for generated columns can be specified in the request
```
export interface V1MetricsViewAggregationDimension {
  name?: string;
  timeGrain?: V1TimeGrain;
  timeZone?: string;
  alias?: string;
}
```

**Comment by ericpgreen2** [comment]
Great, using the `alias` parameter works. Thank you!
