### ISSUE TITLE
Make clickhouse integration compatible with older versions

### ISSUE THREAD

**Issue by k-anshul** [rilldata/rill#4458]
It seems some of our queries are not compatible with older versions. We need to test it against older versions and modify the queries accordingly. If some modifications are not easy we should fail gracefully and specify minimum required version.

**Note** : We can't support clickhouse version before 21.11 (released almost three years ago) since information_schema was only available from that release.

**Comment by vvhungy** [comment]
Let me specify the failed query in my case

> SELECT toTimeZone(date_trunc('WEEK', toTimeZone("report_date"::DateTime64, 'Asia/Saigon'))::DateTime64, 'Asia/Saigon') as _ts_2852d02a58a944c39d28b2a45443946a, COUNT(*) as "total_records", .....


and exception I got from ClickHouse error log:

> DB::Exception: WEEK doesn't look like datepart name in dateTrunc.... 

This compatible issue with older-versions of ClickHouse is that they prefer the datetime unit in lower-case like 'week' not 'WEEK'....
Reference here: https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions#date_trunc

**Comment by vvhungy** [comment]
Let me specify the failed query in my case

> SELECT toTimeZone(date_trunc('WEEK', toTimeZone("report_date"::DateTime64, 'Asia/Singapore'))::DateTime64, 'Asia/Singapore') as _ts_2852d02a58a944c39d28b2a45443946a, COUNT(*) as "total_records", .....

and exception I got from ClickHouse error log:

> DB::Exception: WEEK doesn't look like datepart name in dateTrunc.... 

This compatible issue with older-versions of ClickHouse is that they prefer the datetime unit in lower-case like 'week' not 'WEEK'....
Reference here: https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions#date_trunc
