### ISSUE TITLE
Feat: Copy dimension values in TDD and Pivot

### ISSUE THREAD

**Issue by rillsidd** [rilldata/rill#4490]
**Describe the bug**
In time dimension detail view or in a pivot table, if i am comparing by any dimension, i can not hit shift+click a value to copy the dimension value to clipboard

**To Reproduce**
1. Go to https://ui.rilldata.com/demo/rill-cost-monitoring/customer_margin_dash
2. Click on 'Total Cost' metric to expand to time dimension detail view
3. Compare by 'Cost by App Name'
4. Try to copy any of the table values to clipboard (cannot do).

**Expected behavior**
User should be able to shift+click value to copy to clipboard. This is possible on any dimension table in the main dashboard view, just not in the time dimension detail.

**Comment by mindspank** [comment]
Adding Pivot table to scope

**Comment by mindspank** [comment]
@briangregoryholmes @nishantmonu51 looks like this slipped between sprints, moving it up to current sprint again so we dont miss it.
