### ISSUE TITLE
Runtime: Use a single directory for all instance data

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill#4497]
An instance may currently create files in many different directories – namely in the directory containing the DuckDB file (specified when the instance is created) and in various temporary directories that are created ad-hoc.

We want to centralize all data related to an instance in a single directory (which of course can have any number of subdirectories). This will provide two advantages:
- We can emit a metric of the total disk usage for an instance (to be used for quota/usage/billing tracking)
- We can easily clean up an instance's data when it's deleted

**Comment by begelundmuller** [comment]
I'm not sure what the best way to accomplish this is, but here are some implementation thoughts:
- It would be nice if we could specify a `data` directory as config to the runtime (specified using env vars for cloud and hard-coded to `./tmp` on local). And then each instance gets `{data dir}/{instance_id}` as its directory.
- It would be nice to remove path configuration for DuckDB from the deployment config in the admin service. Instead, maybe the instance's data directory is automatically passed to the DuckDB connector (maybe as a permanent config property similar to `allow_host_access`) and it would automatically create a `main.db` file there. 
  - It might make sense to use a sub-directory based on the connector name. In case we support multiple DuckDB connectors in one project.
- Instead of using `os.TempDir`, we would need to pass the instance's data directory in all the places we use `os.MkdirTemp`

**Comment by esevastyanov** [comment]
> @esevastyanov Any chance we could incorporate this into our current `internal-rill-cloud-metrics` pipeline?

yes, once this is implemented. I can introduce a new metrics or update the existing one.

**Comment by begelundmuller** [comment]
@AndrewRTsao @esevastyanov There is already a follow-up issue on the board for periodically emitting a metric based on the size of an instance's data directory: https://github.com/rilldata/rill-private-issues/issues/284

Regarding billable metrics – I would favor using this metric for GB/hr. The current `db_size` is not too trustworthy, and may become even less meaningful with some of the ETL refactors we are considering.

**Comment by AndrewRTsao** [comment]
Okay sweet we can go with this one then. Given that we are billing on "Rill managed data" for UBP, then this might be a more accurate reflection and having an accurate number that we can provide (or even audit) will be important. 

Given our timelines around pricing rollout though, this will likely need to be something we complete next sprint (especially as it's a dependency for other work). Do we feel that those timelines are reasonable?
