### ISSUE TITLE
Variables from `.env` are not correctly picked on first start

### ISSUE THREAD

**Issue by k-anshul** [rilldata/rill#4523]
Reported on Discord by a Rill user here : https://discord.com/channels/959796421832343562/1220310876825976872/1225625678930776064

**Steps to Reproduce**:

1. Set `olap_connector: clickhouse` in rill.yaml.
2. Set some var in `.env` file like `connector.clickhouse.dsn` 
3. Add a dashboard
4. Restart rill and see that dashboard does not load on first start and complains about missing dsn.
5. Make some changes to see that after edits it can correctly pick `.env` file.

**Comment by AndrewRTsao** [comment]
@k-anshul This is likely a continuation of this previously reported issue: https://github.com/rilldata/rill-private-issues/issues/193

Some further context in Slack here: https://rilldata.slack.com/archives/CTZ8XBQ85/p1709652823373129?thread_ts=1709595523.483879&cid=CTZ8XBQ85

cc @begelundmuller

**Comment by begelundmuller** [comment]
This issue will be resolved when https://github.com/rilldata/rill/issues/4491 is closed, which is scheduled for this sprint. Closing in favor of that issue.
