### ISSUE TITLE
Fix: Incorrect unique value count for column stats

### ISSUE THREAD

**Issue by cdeil** [rilldata/rill#4598]
**Describe the bug**

The unique value count in the columns stats view seems to be incorrect!?

**To Reproduce**
1. rill start on https://github.com/rilldata/rill-examples/tree/main/rill-github-analytics
2. On the left click Sources > "rill_commits_source"
3. On the right click on column "commit_hash"
4. Hover on unique values count

**Expected behavior**

I expect the unique values count 2414 to match the number of rows ( since there don't seem to be nulls or duplicates ), but I see 2375 displayed.

**Screenshots**

<img width="1429" alt="Screenshot 2024-04-14 at 20 30 21" src="https://github.com/rilldata/rill/assets/852409/45bd84bc-3d2f-4a45-9300-7f8170ddb701">

**Additional context**

rill version 0.42.3 – cd0501fe9

Chrome Version 123.0.6312.59 (Official Build) (arm64)

**Comment by begelundmuller** [comment]
Hello @cdeil, the profilijngs stats are only intended to give a sampled/approximate view of the data, so it uses an approximate implementation to get unique value counts (in DuckDB, it uses `approx_count_distinct`). Unfortunately it's not feasible to compute exact profiling stats and still maintain interactive performance on larger datasets.
