### ISSUE TITLE
Alternate visualization types for TDD

### ISSUE THREAD

**Issue by djbarnwal** [rilldata/rill#4639]
This issue keeps a track for pending tasks in custom charts - 

**P0**
- [x] Add support for comparisons
- [x] Support custom formatting
- [x] Custom styled tooltip on hover for all charts

**P1**
- [ ] Scrub zoom
- [ ] Pan
- [x] Bidirectional hover highlighting between charts and table

**Comment by AndrewRTsao** [comment]
As a heads up, there is a lot of excitement in the field about this feature. Both NoCD and Deepgram reacted positively when I gave them a sneak peak of `main`

**Comment by ericpgreen2** [comment]
Putting the UXQA doc here: https://www.notion.so/rilldata/UXQA-Alt-Viz-fb97d9eb1c5c4fb1bfb3328e83008172

**Comment by ericpgreen2** [comment]
Closing in favor of https://github.com/rilldata/rill/issues/4857 and https://github.com/rilldata/rill/issues/4858
