### ISSUE TITLE
Improve consistency when running Rill in read-only mode

### ISSUE THREAD

**Issue by AndrewRTsao** [rilldata/rill#4710]
Currently, when running Rill Developer in read-only mode, there is some inconsistency in what exports are allowed as the data viewer is intentionally not allowed in read-only mode (but you can still export from dimension detail and pivot). We should probably rework the implementation to improve how read-only mode works with Rill to avoid any confusion. 

For additional context, see these threads:
https://discord.com/channels/959796421832343562/959801632151969792/1232436131350577282
https://rilldata.slack.com/archives/C01A9DYP013/p1713907354032759

**Comment by AndrewRTsao** [comment]
> I think rill should try and keep a “user promise” like “whatever is on the screen can be exported” even in read only mode. As a user that’s one of the things  I’ve been impressed with so far is how easy to take what I’m seeing and then export as CSV.

Quick follow up from the community on this topic

**Comment by AndrewRTsao** [comment]
> I think rill should try and keep a “user promise” like “whatever is on the screen can be exported” even in read only mode. As a user that’s one of the things  I’ve been impressed with so far is how easy to take what I’m seeing and then export as CSV.

Quick follow up from the community on this topic cc @mindspank @medriscoll

**Comment by mindspank** [comment]
"Whenever a user exports to excel a angel looses it's wings"

Jokes aside though. Having a full table export to a destination or to local if the size is small enough could make sense. I'd weigh it against if we should just allow dimensions and measures (which aren't always exportable in a flat table) VS the model.

We are soon adding exports for metrics which is one of the last pieces

**Comment by ericpgreen2** [comment]
Closing this as `--read-only` has been [deprecated](https://github.com/rilldata/rill/pull/5992)
