### ISSUE TITLE
Fix: Do not request rill.yaml in rill cloud

### ISSUE THREAD

**Issue by AdityaHegde** [rilldata/rill#4763]
For feature flags we are fetching `rill.yaml` to get the defaults. We cannot fetch this in cloud since read file access will only be given to admins.

**Comment by mindspank** [comment]
If that's the case we need an alternate approach of showing the data table viewer in Cloud

**Comment by AdityaHegde** [comment]
@mindspank The data is available in GetInstance now. We will only be avoiding reading files directly from frontend.
