### ISSUE TITLE
Feat(File Explorer): indicate which files have errors (parse or reconcile)

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#4837]
For any file that has a reconcile or parse error, color the file path red. 

[Figma mocks here](https://www.figma.com/file/Qt6EyotCBS3V6O31jVhMQ7/RILL?type=design&node-id=10347-492108&mode=design&t=hi5YbPnBVuNaPCtz-0)

**Comment by AdityaHegde** [comment]
Done as a part of https://github.com/rilldata/rill/pull/4856
