### ISSUE TITLE
File Exporer: Add menu option to directly duplicate a model in the file view

### ISSUE THREAD

**Issue by smartexpert** [rilldata/rill#4852]
**Is your feature request related to a problem? Please describe.**

At times, you need to create a lot of duplicate models of an existing model to start of as the base layer. In release 0.44.1, this is not very user friendly as you have to navigate to the tables in the left bar, right-click the model you want to duplicate and click 'create new model'.

In addition, adding a new model directly in the file system doesn't work. The file shows up but it's not recognized as a rill model.

**Describe the solution you'd like**
In the new left side bar interface in release 0.44.1, add option to duplicate model in the right-click context menu.

![image](https://github.com/rilldata/rill/assets/1627433/8ba1e058-e372-43a1-805a-05c67cec75f8)

**Describe alternatives you've considered**

**Additional context**
None

**Comment by jaroet** [comment]
And not only a model but also a source and maybe even a dashboard?

**Comment by ericpgreen2** [comment]
Closed by https://github.com/rilldata/rill/pull/5993
