### ISSUE TITLE
Support of DataYAML in alerts

### ISSUE THREAD

**Issue by esevastyanov** [rilldata/rill#4874]
We have a new YAML struct called DataYAML ([code](https://github.com/rilldata/rill/blob/30acfd644230bbdaaacc0b5d0b93acb7701b710c/runtime/compilers/rillv1/parse_api.go#L50)) made available under data: in YAML, which is a generic way to identify some data to load. We use it currently for data for custom APIs and custom charts. We need to add support for it in alerts and reports as well – that will enable adding alerts/reports on top of metrics SQL and custom APIs.

**Comment by begelundmuller** [comment]
Completed
