### ISSUE TITLE
Feat: UI-Based User Invitation

### ISSUE THREAD

**Issue by mindspank** [rilldata/rill#5045]
https://www.figma.com/board/EQiPmBWnt7zVzaywP0lzZx/UI-Based-User-Invitation?node-id=1-765&t=pja18tAWQQLkWBFA-1

https://www.notion.so/rilldata/UI-Based-User-Project-Invitation-Dashboard-Sharing-826f1d3615f14941935c1d57cf7d8df3?pvs=4

**Comment by mindspank** [comment]
Product owner @ericokuma

**Comment by AdityaHegde** [comment]
Related PRs: #5176 #5198
