### ISSUE TITLE
Charts: improved code validation

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#5057]
The following UXQA items relate to validation of the Chart code artifact:
- https://www.notion.so/rilldata/Validation-should-say-when-the-Chart-references-a-field-that-doesn-t-exist-in-the-data-b6d9e03fbade485595901e21986cca8e?pvs=4
- https://www.notion.so/rilldata/Validation-should-say-when-there-s-an-error-in-the-Chart-data-resolver-573a3c15668a442d972705ddf1a8cff4?pvs=4

**Comment by mindspank** [comment]
I don't consider field validation on the vega spec that important though as having to parse every possibility of a data ref in a vega spec will be a major pain.

In addition if we allow for templating of values in vega we would have to parse on the parsed templated spec which is a unnecessary request for the editor currently.

**Comment by ericpgreen2** [comment]
Closing for now
