### ISSUE TITLE
Docs on self hosting

### ISSUE THREAD

**Issue by supermacro** [rilldata/rill#5120]
Are there any docs on how to effectively self-host rill?

What are limitations of self-hosting as well (e.g. features that are in the cloud version vs self-hosted version)?

**Comment by uttam17** [comment]
@supermacro I don't believe there are any ways to self host. You can run it locally though

**Comment by supermacro** [comment]
https://github.com/rilldata/rill/issues/3720#issuecomment-1864219150

https://github.com/rilldata/rill/issues/3740#issuecomment-1865406163

**Comment by mindspank** [comment]
In general you can run Rill Developer via `rill start` with various start-up parameters such as `--readonly` which produces a more end user friendly experience. See https://docs.rilldata.com/reference/cli/start for the full documentation.

As we don't have a user context, nor a backing database, Rill Cloud features such as reports, alerts, bookmarks and encrypted credentials are not available when hosting Rill Developer. 

It should be fairly straightforward to dockerize the CLI and to clone/mount project files and start up.
https://github.com/rilldata/rill/blob/main/Dockerfile is one example, adapt to run rill start as opposed to just serving the backend
