### ISSUE TITLE
Referenced in model navigation fails if destination in a directory

### ISSUE THREAD

**Issue by arunsworld** [rilldata/rill#5122]
Model view has "Referenced in this model" section that shows the sources and models it uses. Clicking tries to navigate to the referenced model/source.

If the model/source is in a directory however, the navigation fails. It appears to assume model/source will always be in the root location.

For instance if the source is abc - navigation happens to /source/abc while the source might actually be in a directory say group, which means it's actually in /source/group/abc

**To Reproduce**
1. Create a source
2. Move source to a sub directory
3. Build a model from the source (Create model button)
4. Click on the source shown under "Referenced in this model"
5. Error: File not found
6. Same issue if reference is another model and that model is in a directory

**Expected behavior**
Expect to be able to navigate to source/model even if its in a directory.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome/safari
 - Version: 0.46.5 and also HEAD

**Comment by mindspank** [comment]
Closed via #5143
