### ISSUE TITLE
Explore Dash is not present with new autoconfig and not populated when restarting an existing project

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill#513]
**Describe the bug**
Explore Dashboard 
1) if you autopopulate the metrics config and then try to go to explore there is no experience. The screen is blank until you refresh. 
2) If you have a project you are working on and quit the application and start again, when you first go to explore it looks like there is no data.  There is no data even when you navigate back and forth between config and explore until you refresh. 

**To Reproduce**
1. Import the example data set
2. shift+click the source to autogenerate the model
3. go to metrics config and select model file, firstflightdate, and click the button to generate measures and dimensions.
5. click on the button to explore and see nothing in the workspace.
6. refresh and the dashboard appears with data
7. quit the application and restart it
8. click on the button to explore and see the explore dashboard with no data inside.
9. refresh and the dashboard appears with data

**Expected behavior**
The dashboard should be a reflection of the metrics config and reactively update the dashboard without the need for refreshing the page.

**Comment by AdityaHegde** [comment]
Fixed in metrics-explore branch.
