### ISSUE TITLE
Deploy from a directory within a repo

### ISSUE THREAD

**Issue by DingoEatingFuzz** [rilldata/rill#5155]
**Is your feature request related to a problem? Please describe.**

I have a repo that contains a Rill project and I would like to deploy the Rill project.

**Describe the solution you'd like**

`rill deploy --path path/to/rill` ought to deploy from the directory while detecting the remote from current working directory.

**Describe alternatives you've considered**

There is no alternative to this aside from separating my data processing from my Rill project or doing all my data processing within Rill. Neither of these are suitable.

**Additional context**

This is what a ran from the root of an existing git repo that has a remote. I'm assuming when it says "no git remote was found" it's looking from within `rill/` instead of cwd.

Being able to choose a path is super normal for these types of CI driven tools (e.g., Vercel).

```shellsession
$ rill deploy --path rill/
No git remote was found.
Rill projects deploy continuously when you push changes to Github.
Therefore, your project must be on Github before you deploy it to Rill.
You can continue here and Rill can create a Github Repository for you or you can exit the command and create a repository manually.

? Do you want to continue? Yes
```

I was honestly pretty disturbed that Rill would casually make a repo under my name. It was so easy to accidentally do and then much harder to undo, given that GitHub doesn't expect you to delete repos very often!

Furthermore, once I messed up and made the project, I had to deal with the weird global project state within the `rill` cli, which I expected to be in my rill.yaml file or something, but is instead just kinda hanging out in the ether.

(But I do love the product, so I'm very willing to roll with bumpy DX stuff like this)

**Comment by DingoEatingFuzz** [comment]
Hmm. I just reviewed the docs and see now that there is a `rill deploy --subpath` for this use case. I guess I just don't use the CLI like the authors intended--I'm not sure when I'd ever use the `--path` option instead of just changing directories. When scripting I guess? Idk. Two cents: maybe `--path` should be `--project-path`.

**Comment by mindspank** [comment]
Deploy should use your working directory and tries to detect a git remote in the root of that directory.

If your rill project is not in the root of the repo then yes - - subpath is the way to go which is also there to support monorepos of projects
