### ISSUE TITLE
Amperwave Druid Big query connector throwing error. 

### ISSUE THREAD

**Issue by harshmohta** [rilldata/rill#5159]
**Describe the bug**

For Amperwave customer we are encountering issues when trying to ingest data from BigQuery. The ingestion task  is throwing an error. Additionally, when the timestampColumn is not defined in the ifconfig, the ingestion process takes significantly longer than expected, running around 4-6 hours for 1 hour of data. I suspect when we don't define the timestampColumn it tries to load all data from Bigquery. 

**To Reproduce**
Added spec without  timestampColumn  defined 
[amperwave_spec_no_timestampColumn.json](https://github.com/user-attachments/files/16021452/amperwave_spec_no_timestampColumn.json)

Also attached the error log where we have defined timestampColumn 
[ERROR_LOG.txt](https://github.com/user-attachments/files/16021469/ERROR_LOG.txt)

**Additional context**
[Error Task Log.](https://druid.ws1.amperwave.rilldata.com/druid/indexer/v1/task/index_parallel_arc_superlogs_pnmmnioc_2024-06-27T20:57:56.069Z/log)

**Comment by egor-ryashin** [comment]
Is `wo-wos-reporting-prod.wo_wos_reporting_superlog_prod.arc_superlogs` a view or a table?

If it's a view then timestamp is required to partition the ingestion (without it will be a slow single-task  ingestion).

**Comment by pjain1** [comment]
The problem is when you add a `timestampColumn` in ioConfig then it throws an exception 
```
java.lang.RuntimeException: com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: request failed: Query error: Syntax error: Expected end of input but got integer literal "00" at [1:124]
```
see the attached task logs

**Comment by egor-ryashin** [comment]
Got it, looking into it.

**Comment by egor-ryashin** [comment]
Fixed here https://github.com/gorillio/rill-druid/pull/1397

**Comment by pjain1** [comment]
@egor-ryashin thanks for the fix. Did a release with the fix - https://github.com/gorillio/rill-druid/releases/tag/rill-29.0.1-24.07.09
