### ISSUE TITLE
Getting "glob pattern exceeds limits" for Athena

### ISSUE THREAD

**Issue by arnavawasthi** [rilldata/rill#5170]
**Describe the bug**
I am using "athena" connector. For a table less than 5gb of size, RILL exported data into DuckDB. But for table size > 10GB, I got following error:
```
failed to ingest source: cannot download parquet output "rill-tmp-f37089ae-fa04-4921-825f-cdb34ecbcd3a/**" glob pattern exceeds limits: would fetch more than 10737418240 bytes
```
As I understand, RILL is executing SQL on Athena and then running GLOB pattern on query results on S3 to ingest and that is where it is running into 10gb limit. Even if I use `glob.max_total_size:` to increase it to 100gb, I still get the same error. It suggests that it is ignoring my new setting. Is there any way to set this globally or make "athena" source to use this setting?

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Edge
 - Version: 125

**Additional context**
I noticed that RILL executed SQL on Athena to ingest and eventually running Glob pattern on s3 source.
```
UNLOAD (select * from TABLE
) TO 's3://s3-prefix' WITH (format = 'PARQUET')
```

**Comment by k-anshul** [comment]
Thanks for the report. 
We merged a fix for this here : https://github.com/rilldata/rill/pull/5177
