### ISSUE TITLE
CLI: Don't prompt for both DSN and parts in `rill env configure`

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill#5200]
We should either have an opinionated prompt (simple path) or ask something like "do you want to specify a DSN or individual connection options?" (advanced path). The advanced path might also enable us to ask things like "do you want to set advanced options"?

See report in [Slack](https://rilldata.slack.com/archives/CTZ8XBQ85/p1720236750951439).

**Comment by k-anshul** [comment]
Few approaches I can think :

1. A lot of tools like airbyte, metabase have just hardcoded database specific properties on UI (at least I saw no network call so this is my assumption). So we could employ something similar on CLI/UI and following path can be taken:
    a. On the CLI we can ask user to set `dsn` first with extra hint that they can chhose to ignore this field and set individual properties. If user set `dsn` skip other properties. 
    ```
    connector.clickhouse.dsn (ignore this if you want to set properties individually)
    ```
    b. Ask user to chhose between `dsn` or individual properties. 

2. Add a special `PropertyType` called `drivers.DSNPropertyType` which should indicate that it is a special property that encompasses all properties. Given most of our connectors will have a `DSN` property this seems like a good type to introduce. If a `DSNPropertyType` is present we can ask user to chhose between two options.

**Comment by k-anshul** [comment]
1.a sounds good to me.

**Comment by begelundmuller** [comment]
It may still seem confusing if you enter a DSN, and it then proceeds to ask for the individual properties. If other tools have hard-coded properties, how about we also just decide on one recommended set of properties to prompt for? We could have a `Prompt bool` on the config keys, and only set it to `true` for the recommended set of config keys to configure.

**Comment by k-anshul** [comment]
> It may still seem confusing if you enter a DSN, and it then proceeds to ask for the individual properties. 

No I meant if the user inputs DSN we can skip prompting for other properties. 

I am fine with adding a `Prompt bool` for now as well with it being set as `false` for DSN. Workarounds exists for advanced users.
