### ISSUE TITLE
Expression Syntax for Filters

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill#5201]
Our metrics APIs accept the `*runtimev1.Expression` type, internally rewritten to `*metricsview.Expression`, for filter expressions. We need a user-friendly way to construct these filter expressions, ideally through a simple SQL-like syntax.

This is primarily needed for custom dashboards, where we need to support components like:
```yaml
type: component

kpi:
  metric_view: someview
  measure: measure_1
  filter: some magic syntax to handle filters
```
But it will also be useful for other things, such as:
- Makes our APIs simpler when we open them up
- Cleaner metrics tests (makes it easier to test more!)
- Nicer demos

The goal is to support a limited SQL syntax that is parsed into to the `*metricsview.Expression` type, basically the reverse implementation of [`ExpressionToString`](https://github.com/rilldata/rill/blob/02d0a46bf6c56389e288a521ca9592596ed92486/runtime/metricsview/query_expression.go#L11-L12) in `runtime/metricsview/query_expression.go`. It doesn't need to support subqueries, but it should support basic operators, for example:
```sql
dim1 = 'val1'
-- {"cond": {"op": "eq", "exprs": [{"name": "dim1"}, {"value": "val1"}]}}

dim1 IN ('val1', 'val2')
-- {"cond": {"op": "in", "exprs": [{"name": "dim1"}, {"value": ["val1", "val2"]}]}}
```

It should also be extensible such that it can support computed functions like `time_floor` in the future.

**Comment by begelundmuller** [comment]
Some miscellaneous thoughts on implementation:
- It would be nice if this could re-use code from metrics SQL
- It would be nice if this could be implemented as a custom deserializer on `*metricsview.Expression`, so when trying to deserialize a value into it (using JSON unmarhsal or `mapstructure`), if the value is a string, it tries to parse it.
- For the proto APIs, the `where` and `having` expressions will either need to be made `oneof`s or we can keep it simple and just have something like `where_sql` and `having_sql` fields as alternatives.

**Comment by mindspank** [comment]
Datetime filters are the absolute most common ones so would be great to get basic datetime filter support in early.
The usual suspects of `date_trunc`, `date_add`, `date_sub` and current_date / current_timestamp / now.

I'm generally not a big fan of magic but something like __time.grain could be a interesting idea, for example
`filter: "__time.year = '2024'"` or `filter: "__time.day > now.day - 30"`

**Comment by mindspank** [comment]
We are also intending to support grafana style timesyntax at some point, https://grafana.com/docs/grafana/latest/dashboards/use-dashboards/#time-units-and-relative-ranges
https://github.com/grafana/grafana/tree/main/packages/grafana-data/src/datetime

Perhaps it would make sense to incorporate that straight away?

**Comment by nishantmonu51** [comment]
We discussed about excluding measure filters out of scope of the initial PR.
