### ISSUE TITLE
Setting up Orb and Stripe for prod

### ISSUE THREAD

**Issue by pjain1** [rilldata/rill#5219]
- Setting up of real plans in Orb with all the quotas (as plan metadata)
- Setting up Rill branding in stripe account
- Link stripe account with Orb account 
- Also product decision on what happens on plan downgrade as trial period may have expired. Is there any free plan ?

**Comment by pjain1** [comment]
> Also product decision on what happens on plan downgrade as trial period may have expired. Is there any free plan ?
@nishantmonu51  mentioned - downgrade can be manual as of now, they will need to contact us

**Comment by pjain1** [comment]
@AndrewRTsao or @ericokuma can someone from fe team or product look into ticket. It involves few tasks -
1. Creating plans in Orb. I have created a runbook that is linked in the comment above, that includes what is expected plan format and how to override quotas for specific customers if needed for trial. The reason being you guys can verify what all quotas we want and what values should be there for each quota as per plan and if anything is missing we can add them. 
2. Add Rill branding in stripe account, Rill already has a account just need to branding. 
3. Link Orb and Stripe accounts - It is just a few clicks here - https://app.withorb.com/settings?tab=connections once stripe account is set.

One question would be about migration of existing customers like bluecargo etc. do we onboard them directly to Teams plan ? would the quotas be sufficient there ? as starter plan quotas may be problematic for them.

**Comment by AndrewRTsao** [comment]
IMO we should consider all existing customers as "grandfathered" into existing agreements we have in place with them and either provide some kind of override or simply treat them as enterprise for the duration of their agreements. For example, we just executed a 6 month contractual renewal with BlueCargo so this will be disruptive and contentious if we suddenly shifted them to our new self-serve pricing. Come renewal time though, this should give Sales more leverage though as they will either have to fall back to our existing self-serve pricing or sign a proper enterprise agreement with us. 

cc @rillsidd so we can think through precisely how we handle our cohort of existing RC customers.

**Comment by pjain1** [comment]
Since all orgs need to be attached to a Plan once Orb integration is live, we can just assign them to Enterprise plan or some other internal plan ? This plan can be non public/no default plan in Orb with all quotas set to -1 (unlimited)

**Comment by pjain1** [comment]
There has been discussions going on at multiple places, I have put down some points that needs decision for moving forward on [this](https://www.notion.so/rilldata/Orb-Plans-Runbook-c57133e70d874ec991bc97c665c399f4?pvs=4#d4d920d0f93c477f8b6097023b66a22b) section of Notion doc, lets finalise.

**Comment by AndrewRTsao** [comment]
Sounds good. Agreed we can add to a default enterprise placeholder plan. Will review and add comments on the Notion doc

**Comment by nishantmonu51** [comment]
@ericokuma : Can you help here ? Would be good for you and @pjain1 to get on a call and set these up in a working session.

**Comment by pjain1** [comment]
This is mostly done, @ericokuma will finish this once he gets clarification on few pending items.
