### ISSUE TITLE
The dimension detail view does not show comparison data when ordering by the dimension value

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill#5236]
If you enable comparisons, the dimension detail view usually shows comparison values. But if you sort the view by the dimension value column, then it stops requesting comparison data.

<img width="2693" alt="Screenshot 2024-07-10 at 09 57 17" src="https://github.com/rilldata/rill/assets/791356/a700ee27-89a3-4696-ab64-cbec88ab1b5c">

**Comment by mindspank** [comment]
That's the intended behavior https://rilldata.slack.com/archives/C01A9DYP013/p1721126464998039?thread_ts=1721123571.175939&cid=C01A9DYP013
