### ISSUE TITLE
Dashboard filter search is not working for druid based dashboards

### ISSUE THREAD

**Issue by rohithreddykota** [rilldata/rill#5247]
**Describe the bug**
Dashboard filter search is not working for druid based dashboards. When user search for dimension values, dash is using `ilike` for fuzzy search. It is broken wherever search can be used to find the values in the dashboard. 

**To Reproduce**
1. Go to a druid backed dashbaord.

2. Click on 'add filter' 
<img width="272" alt="image" src="https://github.com/rilldata/rill/assets/25232312/64a65133-6c14-4bff-975e-796295056a65">

3. Try to look for any interested value

4. See 400 error in DevTools Console.

**Error Message**
```
map[category:INVALID_INPUT context:map[column:743 endColumn:781 endLine:1 line:1 sourceType:sql] error:druidException errorCode:invalidInput errorMessage:No match found for function signature ILIKE (line [1], column [743]) persona:USER]
```

**Expected behavior**
The filter must show available values. 
<img width="348" alt="image" src="https://github.com/rilldata/rill/assets/25232312/7ed59dd3-cb30-433b-a4fa-98e7b235d1f4">

**Comment by begelundmuller** [comment]
Closed by https://github.com/rilldata/rill/pull/5252
