### ISSUE TITLE
Detect default Git branch during deploy

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill#5270]
Rill currently defaults to using `main` as the production branch in Git during the first deploy from a Github-connected projected. We should infer the default branch from the repository instead.

**Comment by k-anshul** [comment]
This is already implemented here : https://github.com/rilldata/rill/blob/6c4acf1873911fbe83635102c5d9451c81c2dffa/cli/cmd/deploy/deploy.go#L233-L234

I also tested and we are inferring the default branch from the repository.
