### ISSUE TITLE
`rill.yaml`'s `ignore_paths` does not appear to be working

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#5280]
In this case, I wouldn't expect to see `ignore_me.csv` in the File Explorer. I've restarted the application. Is there something simple I'm missing?

<img width="725" alt="image" src="https://github.com/user-attachments/assets/bd0707ff-1a4e-4c03-81c2-cdfd504f5780">

**Comment by k-anshul** [comment]
I think the latest behaviour is that these files will be ignored by Parser but would still be available for viewing in editor.
cc : @begelundmuller

**Comment by ericpgreen2** [comment]
Yeah, fixed by adding the leading slash and restarting the app.

<img width="589" alt="image" src="https://github.com/user-attachments/assets/b89a7b99-771f-4273-844a-e914e5ba65cb">
