### ISSUE TITLE
Adding Percent/Absolute Change to Pivot table, and/or export from measure table

### ISSUE THREAD

**Issue by royendo** [rilldata/rill#5307]
**Is your feature request related to a problem? Please describe.**
Desire to export a dataset with the percent/absolute delta displayed, like in the measure table below:

![Screenshot 2024-07-18 at 16 22 48](https://github.com/user-attachments/assets/cfa1da6c-35a4-464c-a1fb-a9d3989c3fcf)

The export function exists in a pivot table, but doesn't exist for the measure table. E

**Describe the solution you'd like**
Solution 1: Add export table option for a specific measure table that already has the percent/absolute change metric. 

Solution 2: Add the percent/absolute change feature to pivot table since export is already supported.

**Describe alternatives you've considered**
Unsure of any alternatives

**Additional context**
FR from a user

**Comment by nishantmonu51** [comment]
@lovincyrus : You may hv already fixed this one ?

**Comment by lovincyrus** [comment]
> @lovincyrus : You may hv already fixed this one ?

Yes - Fixed in https://github.com/rilldata/rill/pull/5427
