### ISSUE TITLE
Feat: Support UI state in Public Links

### ISSUE THREAD

**Issue by mindspank** [rilldata/rill#5313]
We should support UI state for Public Links similar how we support it for Bookmarks. 

AC:
* A user can choose to save UI state as part of the public link. 
* Saving state should default be on

**Comment by begelundmuller** [comment]
Tracking the platform support for this here: https://github.com/rilldata/rill/issues/5271

**Comment by ericpgreen2** [comment]
[Linking our Slack convo](https://rilldata.slack.com/archives/C01A9DYP013/p1723468942503469) regarding what should happen when sharing the Dimension Detail Table and Time Dimension Detail
