### ISSUE TITLE
Public URLs: Add a page to list/manage

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#5328]
[Figma mock](https://www.figma.com/design/Qt6EyotCBS3V6O31jVhMQ7/RILL?node-id=15019-622855&t=TVF5Fzm10rNjF5Ik-0)

Requirements
- Create a page at `ui.rilldata.com/[org]/[project]/-/public-urls`
- List all Public URLs in a table
- Include:
    - dashboard to which the URL applies
    - expiration time (if any)
    - a delete action

Notes by Cyrus
- Ref: https://github.com/rilldata/rill/pull/5283
- Ref: https://www.notion.so/rilldata/Support-for-shared-filtered-dashboard-URLs-6490b207cb8e43278b9992ebf11d6195#c4bbda6182514673a6857500bd2be820
- Ref: https://docs.rilldata.com/notes/0.47#public-links
- Ref: https://rilldata.slack.com/archives/C04JP568RR6/p1722288927983179
- Can ping benjamin for platform support

**Comment by lovincyrus** [comment]
How do we get public urls atm? @ericpgreen2 

I see `rill public-url` from [the doc](https://docs.rilldata.com/reference/cli/).

![Image](https://github.com/user-attachments/assets/be599ea7-d9ff-40a8-8304-2243a195ebd0)

And `rill share-url` in the latest CLI build.

![Image](https://github.com/user-attachments/assets/5f0ba713-fc39-4d08-a781-a02e27a21a5b)

**Rill version**
`rill version 0.47.5 (build commit: 5e3bb02b9 date: 2024-07-19T05:16:50Z)`

**Comment by ericpgreen2** [comment]
> How do we get public urls atm? @ericpgreen2

In our v47 release notes, check out the gif that shows how to create them: https://docs.rilldata.com/notes/0.47
