### ISSUE TITLE
File Explorer: Cancel drag events of directory/file when the native context menu is opened

### ISSUE THREAD

**Issue by lovincyrus** [rilldata/rill#5337]
**To Reproduce**
1. Go to File Explorer
2. Hover over a directory
3. Right-click to open the native context menu
4. Press Esc to close the native context menu
5. The current directory will be stuck in a 'dragging' state

**Expected behavior**
The drag events of the current directory should be removed when the native context menu is opened.

**Screenshots**
Right click to open native menu when on a directory
![CleanShot 2024-07-24 at 15 47 07@2x](https://github.com/user-attachments/assets/d4abd673-e27c-4b9e-b453-3f8b8a2dbff3)

The directory will be stuck in a 'dragging' state
![CleanShot 2024-07-24 at 15 47 35@2x](https://github.com/user-attachments/assets/9182d39d-9a44-4d13-8ea6-41723287e519)

**Recording**

https://github.com/user-attachments/assets/89620f56-67c9-497a-b75e-b3cb7eb9c7fc

**Comment by mindspank** [comment]
Thanks for the report!
We'll get it fixed in our next sprint.
