### ISSUE TITLE
Add further usability to User groups

### ISSUE THREAD

**Issue by royendo** [rilldata/rill#5349]
**Is your feature request related to a problem? Please describe.**
The FR is two parts.
1) Adding a group assignment to a user invite.
```
rill user add --email username@domain.com --role viewer --group viewer_group
Error: user not found (InvalidArgument)

rill user add --email username@domain.com --role viewer
Invitation sent to ... as "viewer"

rill user add --group viewer_group --email username@domain.com
Error: user not found (InvalidArgument)
```
In the above case, the user has to accept the invitation before a group can be added which makes for a undesired behavior, having to wait after accepting the invite to be assigned a group.

---

2) Adding support for non-org users to be added to usergroups.
```
rill user add --email username@domain.com --project my-rill-project --role viewer

rill user add --group viewer_group --email username@domain.com
Error: user is not a member of the organization (InvalidArgument)
```
The above errors as the user is not part of the organization, only part of the single project.

**Describe the solution you'd like**
1. A user should be able to be invited with a group assignment so when accessing the environment, they immediately can start working.

2. A user that is not part of the organization, only a project, should also be able to be added to a usergroup, adding more functionality.

**Describe alternatives you've considered**
Not sure if there's any direct workarounds... 
1. Wait for accept, then set the groups afterwards.
2. Manually add the user /access to different projects

**Additional context**

![project-access](https://github.com/user-attachments/assets/540bd488-0f62-44f2-bb67-ff4b5d344da6)

**Comment by begelundmuller** [comment]
Also see this Slack [thread](https://rilldata.slack.com/archives/CTZ8XBQ85/p1721781680976799) for more context. 

I think a good starting point here is to just add support for group assignment in the `org_invites` table.

**Comment by pjain1** [comment]
> If trying to add a user to a group in an org they don't belong to, also add them to the org (with a prompt to confirm)

So an existing Rill user cannot be of an org usergroup without being assigned a role on org ? Then for non existing Rill user as well we make them part of org first and then assign them to the group ?

**Comment by begelundmuller** [comment]
> So an existing Rill user cannot be part of an org usergroup without being assigned a role on org ? 

Yes – you can *only* be in a usergroup in an org if you are a member of the org.
