### ISSUE TITLE
Support comparisons with time as a dimension

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill#5361]
Currently, comparisons are computed using a subquery for the base and comparison time range, which is joined on the dimension values using `IS NOT DISTINCT FROM` (happens [here](https://github.com/rilldata/rill/blob/8054854a54f58fc43093567e2a176f341b181a88/runtime/metricsview/astsql.go#L151)). This works well for comparing regular dimensions (e.g. `base.country IS NOT DISTINCT FROM comparison.country`), but it does not work if comparing with a time dimension (e.g. this never matches because the comparison time range is different: `base.time__day IS NOT DISTINCT FROM comparison.time__day`).

Currently, this is not a problem because the application only needs the data for the time charts, and it just makes two separate queries for the time range and computes the comparisons client-side. But they now want to support comparisons on the time dimension in the pivot table.

The way I would propose handling this is that if comparing by a time dimension, then it can look at the query's `time_range` and `comparison_time_range` and determine an offset between them. And then use `base.<time field> IS NOT DISTINCT FROM comparison.<time field> + INTERVAL '<offset>'` to do the comparison join.

It will probably be somewhat tricky to infer a correct comparison time offset. One approach would be to subtract the `start` time of the base time range from the comparison time range's, rounding to the time dimension's granularity (as set in `time_floor.grain`), and then using that as the join offset.

There may also be a possible approach that uses the `iso_duration` and `iso_offset` fields, but the logic around those and how they interplay between the base and comparison time ranges is slightly tricky, so that would need to be taken into account. They are also not always set, e.g. the UI often sends fixed start and end timestamps: https://github.com/rilldata/rill/blob/8054854a54f58fc43093567e2a176f341b181a88/runtime/metricsview/query.go#L117-L123

**Comment by egor-ryashin** [comment]
FYI, there can be multiple time dimensions like timestamp_day, timestamp_year in a single query.

**Comment by egor-ryashin** [comment]
BTW, it doesn't cover time comparison for a measure filter - how could we approach that?

**Comment by begelundmuller** [comment]
> BTW, it doesn't cover time comparison for a measure filter - how could we approach that?

Can you provide an example of this issue? Not entirely sure what you mean.

**Comment by begelundmuller** [comment]
Closed by https://github.com/rilldata/rill/pull/5475
