### ISSUE TITLE
Public URLs: Support encrypted secret in magic auth tokens

### ISSUE THREAD

**Issue by lovincyrus** [rilldata/rill#5375]
The public URLs we create are currently ephemeral. We can store the encrypted magic token in the database so that we can query and list them in the public URLs table.

This is blocking https://github.com/rilldata/rill/pull/5366

Related: https://github.com/rilldata/rill/pull/5071, https://github.com/rilldata/rill/pull/5175, https://github.com/rilldata/rill/pull/5163

#### NOW
- [ ] Add `EncryptedToken` or `Secret` in `magic_auth_tokens` table
- [ ] Store encrypted token upon `IssueMagicAuthToken`
- [ ] https://github.com/rilldata/rill/pull/5402#discussion_r1705353488

#### References

`magic_auth_tokens`
| encrypted_secret  |
| ------------- | 
| 1Vc74Wk790Ck0p27u8cJdGvts1eYivSWlZAeCCdRLuMEvFZWdFLJE2  |

Construct http://localhost:3000/{org}/{project}/-/share/{magic_token}

List magic tokens `/v1/organizations/${organization}/projects/${project}/tokens/magic`

```go
// admin.swagger.yaml
// /v1/organizations/{organization}/projects/{project}/tokens/magic
// lists all the magic auth tokens for a specific project.
ListMagicAuthTokens

// admin-service.ts
// IssueMagicAuthToken creates a "magic" auth token that provides limited access to a specific filtered dashboard in a specific project.
adminServiceListMagicAuthTokens

// admin-service.ts
getAdminServiceListMagicAuthTokensQueryKey

// auth_token.go
// IssueMagicAuthToken generates and persists a new magic auth token for a project.
IssueMagicAuthToken

// database.go
FindMagicAuthTokensWithUser(ctx context.Context, projectID string, createdByUserID *string, afterID string, limit int) ([]*MagicAuthTokenWithUser, error)
FindMagicAuthToken(ctx context.Context, id string) (*MagicAuthToken, error)
FindMagicAuthTokenWithUser(ctx context.Context, id string) (*MagicAuthTokenWithUser, error)
InsertMagicAuthToken(ctx context.Context, opts *InsertMagicAuthTokenOptions) (*MagicAuthToken, error)
UpdateMagicAuthTokenUsedOn(ctx context.Context, ids []string) error
DeleteMagicAuthToken(ctx context.Context, id string) error
DeleteExpiredMagicAuthTokens(ctx context.Context, retention time.Duration) error
```

**Comment by begelundmuller** [comment]
Just adding some context here. This issue requires support for column-level encryption in Postgres, which is also something we need for credentials. The requirements are:
- Take an approach that also works for encrypt credentials (to avoid needing to manage more than one set of encryption keys for column-level encryption)
- The encryption keys need to be externally configured (e.g. with an environment variable or key file) and we need to support key rotation for them. So we probably need to persist a key ID alongside the encrypted value.
- We also need to think about encryption of credentials on the runtimes. They should either use the same encryption scheme, or they should pull variables from the encrypted store on the admin service on each restart.

In terms of how to implement the cryptography, we should consider using the `pgcrypto` Postgres extension and handling it in the DB itself.
