### ISSUE TITLE
Sample on Alerting UI is wrong for All-time

### ISSUE THREAD

**Issue by royendo** [rilldata/rill#5393]
**Describe the bug**
When creating an alert, there is a sample of whether the alert will run. When using all-time the UI says, "Given the above criteria, this alert will not trigger for the current time range." however this is incorrect (see screenshot(

**To Reproduce**
1. Go to 'Alert'
2. Set an alert when dashboard is on all time timeseries 
3. Create check on measure split by dimension

**Expected behavior**
When using other time filters, i see the correct data on whether the alert will be sent or not

**Screenshots**
![failing alert check](https://github.com/user-attachments/assets/c6037358-bfb4-494b-b53b-74bc09102f73)
![alert settings](https://github.com/user-attachments/assets/41275753-2fee-4a47-950c-21c92361d59f)
![working alert check](https://github.com/user-attachments/assets/ffe16ac7-e8a5-4a73-959d-971c8fdb6ed9)

**Comment by nishantmonu51** [comment]
@AdityaHegde : Can help provide pointers here for where to look into the codebase.

**Comment by lovincyrus** [comment]
Thanks for reporting this, @royendo! I'm using "All time" and other time selectors like "Last 24 hours" as part of the repro steps. Could you clarify what you mean by the error in Step 4?

https://github.com/user-attachments/assets/3e76b1b6-eaf1-4657-bab3-68f41e3cc5a1

**Comment by royendo** [comment]
Hello!

Yeah, step 4 could've been written out better 😂

In my case, when using all time, all of the unique commits were set to 1, which is not the case! So when I go to the next step and set to greater than 5, all the users disappears.

However any other time filter would accurately show the unique commits of a user.

**Comment by lovincyrus** [comment]
I think I see it now.

![Image](https://github.com/user-attachments/assets/dc1bfa87-0cbf-4b12-9e54-efa6c3b30f5c)

https://github.com/user-attachments/assets/29101180-8788-40df-a442-04e3e0cde55c

**Comment by royendo** [comment]
Right, there is a false negative. 

In your video, when you set value > 1, there are many users with >1 commits but according to the UI it says 'this alert will not trigger`, which is incorrect

**Comment by lovincyrus** [comment]
I reviewed the issue again and couldn't repro the same behavior on the latest `main`.

`All Time`

https://github.com/user-attachments/assets/c395bcee-5dbf-4841-af62-1c8348caaccd

`Last 24 Hours`

https://github.com/user-attachments/assets/4393a5f1-8af4-4a4f-adfb-2f8ce097a142

Can you confirm? @royendo
