### ISSUE TITLE
Ability to send alerts to project admins on reconcile failures

### ISSUE THREAD

**Issue by nishantmonu51** [rilldata/rill#5410]
When a reconcile fails due to an ingestion error, we need the ability to send an alert to project admins so that they can take necessary action to fix the project.

**Comment by begelundmuller** [comment]
An idea for solving this is by adding a resolver for the a project's reconcile status, which could be used to configure an alert. Something like this:
```yaml
type: alert
refresh:
  cron: 0 * * * *
data:
  project_errors: {}
notify:
  email:
    recipients: [benjamin@example.org]
