### ISSUE TITLE
Improve error messages to include file name having ingestion issues 

### ISSUE THREAD

**Issue by nishantmonu51** [rilldata/rill#5411]
If a malformed CSV file gets added to a directory, it can fail data ingestion. 
In such case the error currently doesn't include the exact file name causing issues. 
Add the corrupt file name to the error returned. 
Optionally also add the ability to skip corrupted files as well.

**Comment by begelundmuller** [comment]
If this is caused by DuckDB not showing the file name, we should consider just raising the issue in their issue tracker instead.

**Comment by k-anshul** [comment]
Nothing to be done on this from our side. This will already be part of error messages. Sample below :
However the file name is trimmed. 
<img width="1282" alt="image" src="https://github.com/user-attachments/assets/e7e7052d-1545-456a-85fa-18f12c2b1fdb">

**Comment by k-anshul** [comment]
The file name being trimmed will be handled in a separate issue in https://github.com/rilldata/rill/issues/5604
