### ISSUE TITLE
Improve storage limits check

### ISSUE THREAD

**Issue by k-anshul** [rilldata/rill#5414]
1. The current storage limits check is spread across multiple transports and model executors. 
2. This leads to lot of duplicated code with chances of multiple goroutines running in background ensuring size computations. 
3. The implementation is also incorrect in some case like in `duckdb.execWithLimits`
4. Overall the implementation is incorrect when multiple reconciles happen in parallel.

There should be a single place to enforce this check. I propose following solution.

1. Controller maintains a flag `limitExceeded` which maintains state of limits.
2. Controller runs a background goroutine that periodically checks the size of instance's data directory and updates the flag.
3. When the size is exceeded it also cancel all running invocations.
4. The reconcilers check for the flag whenever they start generating new data.

Another solution is to skip storage checks for now.
Our disk limits are somewhat relaxed and we are expected to run into other issues(like memory issues) before we run into disk limits so we can avoid enforcing systematic limits as well and directly setup alerts on `instance_data_dir_size` emitted periodically from runtime.

**Comment by pjain1** [comment]
I wonder if same thing can be used to check the size of just db files and warn on going above 100% of the quota and hard fail on going above 150% that product is requesting.

**Comment by begelundmuller** [comment]
Some thoughts on this:
- I think it's a good idea to move it to the controller.
- This will probably only be used for the medium-term since long-term we want to move fully to external databases and avoid having a dependency on a single runtime with a single disk (necessary for HA).
- A problem with cancelling invocations and stopping the controller is that it doesn't give people a chance to fix the issue (e.g. by reducing data and re-ingesting). Can you think of a workaround for this? If not, I think we should just log an error for now, but not take any automated action.

**Comment by k-anshul** [comment]
> A problem with cancelling invocations and stopping the controller is that it doesn't give people a chance to fix the issue (e.g. by reducing data and re-ingesting). Can you think of a workaround for this? If not, I think we should just log an error for now, but not take any automated action.

Good point. There can be some workaround like not stopping the controller and allowing manual `refresh` trigger to succeed but scheduled refreshes to fail but given we only need this solution for medium term I think its okay to just log an error for now. We can enhance this further if we want automated action for medium term as well.

**Comment by k-anshul** [comment]
This got me thinking if we just want to add a log message which I believe will trigger an alert we can directly create an alert.
We are already publishing `data_dir_size_bytes` metrics for `instance`. We can look up slots for the instance and trigger an alert based on allowed limit.
Given this is not a critical alert it should be okay to rely on same system to trigger an alert.

**Comment by begelundmuller** [comment]
Are you talking about a Zap log that would trigger an alert in Datadog? Or creating an alert in the `rill-cloud-metrics` dashboard based on the `data_dir_size_bytes`?

Either approach sounds good to me. I think the task list for this PR then becomes:
- [ ] Setup a dashboard or Slack alert for projects that have exceeded their data quota
- [ ] Remove the existing faulty storage limit checks

**Comment by pjain1** [comment]
> A problem with cancelling invocations and stopping the controller is that it doesn't give people a chance to fix the issue (e.g. by reducing data and re-ingesting).

Just to understand this better, can they not fix their source/model to reduce data and do a project reset ? (although recently we removed ability for users to reset)

**Comment by k-anshul** [comment]
> Just to understand this better, can they not fix their source/model to reduce data and do a project reset ? (although recently we removed ability for users to reset)

Yes that was also possible with the reset command. We can also take this approach if in future we need automated handling otherwise allowing manual refreshes and blocking scheduled refreshes can also be considered.
