### ISSUE TITLE
Wildcard or Free Text Filter for Dimensions

### ISSUE THREAD

**Issue by ap76ap** [rilldata/rill#5541]
Firstly thanks for your work on Rill - its a fantastic tool and we enjoy using it everyday. We keep Rill up to date and run it against our Clickhouse instance.

We work with large Dimensions - they may have many thousands or even hundreds of thousands of unique values per dimension.

When trying to filter in Rill on these large dimensions often I'm unable to find the value of interest in the limited list of values present in the filter drop-down.

As a fall back I also try to set the required filter from the Dimension - Expand Table - view, which often shows more values and allows for sorting alphabetically, forward and reverse, but even then unless the dimension value I'm looking for is near the start, or the end alphabetically I'm unable to find and set it as I would like.

Would it be possible to provide a "wildcard" string that would then be applied as a filter to the dimension (using LIKE or CONTAINS or similar). That way I could enter PPP for example and all dimension values containing PPP would then be filtered to.

Alternatively having a free text component to the filter drop down allowing explicit entry of the dimension value to filter on would also help in the case I'm describing.

**Comment by mindspank** [comment]
Hey, we do currently perform a wildcard search when searching in a dimension. So if you perform a search and hit enter it would select/filter by all matching entries

**Comment by ap76ap** [comment]
Hi @mindspank - thanks for the reply - from your notes I managed to find it! 

For others who might end up here - the wildcard search against a dimension can be accessed from the detail screen for a chosen Metric when a Comparison Dimension is selected.


<img width="1045" alt="image" src="https://github.com/user-attachments/assets/d2826df9-8906-4bc1-ba6d-133f1c5e92ad">
