### ISSUE TITLE
Cloud UI: Environment Variable Management

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#5583]
Part 1 from the [PRD here in Notion](https://www.notion.so/rilldata/Environment-Variables-management-UI-42304f145b07410d86c2a523496aa6bc?d=d8eaf90ee0a1414b8a2a49fbd0b75c4f#e4a772f27fad420ca3466fa6c5ea99d3)

Revisit after https://github.com/rilldata/rill/pull/5929

**Comment by begelundmuller** [comment]
FYI https://github.com/rilldata/rill/pull/5929 has now been merged

**Comment by lovincyrus** [comment]
> FYI https://github.com/rilldata/rill/pull/5929 has now been merged
> 
> 

Will prioritize the env var work next, thanks!

**Comment by lovincyrus** [comment]
Added in https://github.com/rilldata/rill/pull/6012
