### ISSUE TITLE
Release: Update version number in `package.json` files

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#5592]
We should update our `rill-ui.yml` GitHub Action so that it writes the release number to our various `package.json` files:
- Root `package.json`
- `web-admin/package.json`
- `web-common/package.json`
- `web-local/package.json`

**Comment by himadrisingh** [comment]
GHA will be confusing, we can try using bumpversion to update these files and create a tag for the release

**Comment by Kavinjsir** [comment]
Hey @ericpgreen2, just wanted to let you know that after checking things out on the infra side, we've decided to stick with manual updates for now.

For releases, automating the version alignment across files between branches is a bit tricky at this stage.

So I'm gonna handle the updates manually from the main branch and push changes to the release branch, just like we do in our usual dev flow.

We’ll pick up some insights along the way and keep refining our approach.

If you have any suggestions or there’s anything specific you’d like to see, definitely give us a shout 😃
