### ISSUE TITLE
Release: make application version number accessible to the frontend

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#5594]
During our build process, we should write the application's version number (pending https://github.com/rilldata/rill/issues/5592)  somewhere where it's accessible to the frontend application code.  We could write it to a `version.json` file or set it as an environment variable.

Then we can:
1. Show the Application version number somewhere in the UI
2. Include the Application version number as context to our telemetry

**Comment by himadrisingh** [comment]
Env variable seems to be better solution, as we dont need to commit the file then.

https://github.com/rilldata/rill/pull/5610
