### ISSUE TITLE
`vite dev` hangs

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#5702]
We've recently started having problems running the app via Vite's dev mode with HMR. Seemingly, the dev server spontaneously stops serving the application, and the only remedy is to restart the dev server.

I've seen this error message in the browser console:
![Image](https://github.com/user-attachments/assets/8682497d-a3a4-415f-bef2-d7f1c1a526b8)

Some thoughts on paths forward:
- Upgrade to SvelteKit 2.0, which upgrades from Vite 4 to Vite 5.
- Dig into Vite's server settings. Like, maybe pruning the watched files could improve performance.
- Is this a problem with port 3001? On port 3000, I seem to have fewer HMR crashes, but my browser consistently hangs whenever I restart the app on a new project.

See https://github.com/vitejs/vite/issues/11468

**Comment by mindspank** [comment]
Ah so that's what it was! Thought it was going insane the other day 😂

**Comment by ericpgreen2** [comment]
Closed by https://github.com/rilldata/rill/pull/5797
