### ISSUE TITLE
null value in explore vs null value in TDD

### ISSUE THREAD

**Issue by royendo** [rilldata/rill#5707]
**Describe the bug**
The "null" row in TDD is not italicized like it is in explore. To create consistency, have the TDD "null" row also italicized. 

<img width="400" alt="image" src="https://github.com/user-attachments/assets/451849f6-1176-493a-8d68-219442d634f0">
<img width="385" alt="image (1)" src="https://github.com/user-attachments/assets/685e1eb7-da49-4ae3-86ce-71b11033ea6b">

Angel Requested
https://rilldata.slack.com/archives/C07KSF2DPPV/p1726498803956059?thread_ts=1726097126.515679&cid=C07KSF2DPPV

**Comment by ericpgreen2** [comment]
Closed by https://github.com/rilldata/rill/pull/5945
