### ISSUE TITLE
Support `TTL` for ingested data

### ISSUE THREAD

**Issue by k-anshul** [rilldata/rill#5773]
Given now we support incremental models with splits, it will be good to also allow users to set a TTL on their data.
A common use case will be to load data for last X days for serving dashboards. Request raised by @harshmohta

**Comment by k-anshul** [comment]
For clickhouse this is possible with native support, for duckdb need to build support

**Comment by begelundmuller** [comment]
Given that we can leverage ClickHouse's native support here, I think we can close this issue for now. In the future, we may want to support retention policies (probably a SQL filter that matches rows to drop) generically, which would also solve this problem for DuckDB.
