### ISSUE TITLE
APIs for Cloud Environment Variable management

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#5804]
https://www.notion.so/rilldata/Environment-Variables-Cloud-Management-Table-API-Design-10cba33c8f578098acb3c0aebce18bcd

**Comment by begelundmuller** [comment]
Updated the document with a detailed proposal here: https://www.notion.so/rilldata/Platform-support-for-environment-variables-UI-10cba33c8f578098acb3c0aebce18bcd.
