### ISSUE TITLE
Docs: Update url path of environment variable management

### ISSUE THREAD

**Issue by lovincyrus** [rilldata/rill#6010]
`https://docs.rilldata.com/tutorials/administration/project/credential-envvariable-mangement` → `https://docs.rilldata.com/tutorials/administration/project/credential-env-variable-management`

**Comment by lovincyrus** [comment]
I think I still see `mangement` in there. It should be `management`.

**Comment by royendo** [comment]
oops, btw do you need this done faster or is v51 docs okay
