### ISSUE TITLE
Label deprecated in Code based for measures but we still use in the UI 

### ISSUE THREAD

**Issue by royendo** [rilldata/rill#6140]
**Describe the bug**
Are we using Label or Display Name moving forward, UI and YAML are incosistent

https://github.com/rilldata/rill/blob/68383e1d3cf2d526d3a1112c1ee71e32153abaaa/runtime/compilers/rillv1/parse_metrics_view.go#L47

**Expected behavior**
Change the UI to Display Name for less confusion

**Screenshots**
![Screenshot 2024-11-22 at 14 26 28](https://github.com/user-attachments/assets/b1686c60-5adc-422c-b17a-004a1887a362)

**Comment by mindspank** [comment]
The actual display columns needs changing but we should also:

- Map to display_name key in yaml files
- For metric views that was created pre-deprecation we should "migrate" a measure or dimension to use display_name instead of title/label when edited.

**Comment by ericpgreen2** [comment]
To confirm, is the UI supposed to read "Display name" not "Label"? @jkhwu

**Comment by mindspank** [comment]
Yes, as per design mocks its Display name. 
We have also deprecated the actual yaml property `label` and `title` in favour of `display_name`
