### ISSUE TITLE
Separate release process for docs and binaries

### ISSUE THREAD

**Issue by nishantmonu51** [rilldata/rill#6157]
Binary release and docs releases would be separate
- Release manager would need to release both binary and docs 
- No continuos doc changes from main pushed to docs
- In between release doc patches would be similar to release patch, backport to release branch 

Changes - 
- Stop continuous doc push on every commit to main 
- Add a new manual action to push doc from a given branch 
- Update release runbook

**Comment by nishantmonu51** [comment]
+cc @royendo

**Comment by himadrisingh** [comment]
* Docs will be published on tags 
* there is also a way to push patch from any branch

**Comment by himadrisingh** [comment]
https://www.notion.so/rilldata/Release-Run-Book-20a4afb8f2f64d06814a0c89d51bfdcf?pvs=4#14bba33c8f57806dba9aeb8cc5ad3dfd
