### ISSUE TITLE
create error state in metrics config if there are no viable dimensions, or ignore entirely

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill#657]
Currently, if I create a dataset that has no viable dimension columns (no `CATEGORICALS` basically) we don't let the user go to the dashboard. 

We should do one of two things:
1. surface an error the the user in the metrics config
2. let them keep on going w/o dimensions to the dashboard

My vote is for 2. They shouldn't have to define dimensions to get line charts.

**Comment by bcolloran** [comment]
Yeah I think you are right, (2) is better. based on one of the conversations we had last week, it feels like we're evolving our thinking from: _Explorer is line charts + leader boards_ to: _Explore can still have value as just line charts or just leader boards_.

In the latter case, I do kind of wonder if we want to surface some kind of messaging or indicator for users short circuit to Explorer and arrive there in only line charts or only leader boards mode to let them know that Explorer is capable of more functionality if you give it a data set with the right kind of structure. This might be especially important during a first-run experience -- if we shortcut them to a dashboard that has just one half or the other of the core functionality, we probably want to somehow let let them know that more functionality exists.

Some random brainstorms following from this:
- do we want to enable specific modes with separate layouts for _just line charts_ and _just leader boards_?
- Or do we want to just have the one layout (the current one: line charts left, leaderboards right)
    - in this case, we could consider using the empty space as the place where we provide messaging about the unused capability, and how to activate it
- we could also imagine like compose/publish modes for Explorer, such that the messaging about the unused capability is not shown in a dashboard that is in publish mode (probably e.g. any dashboard that is shared would be in published mode)
