### ISSUE TITLE
Postgres SQL syntax styling is misdirecting users in how to omit columns in duckDB SELECT statements.

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill#662]
**Describe the bug**
Postgres SQL syntax styling is misdirecting users in how to omit columns in duckDB SELECT statements.

**To Reproduce**
1. open a model
2. type `SELECT * EXCLUDE`
3. See that `EXCLUDE` has no color styling
4. delete and type `SELECT * EXCEPT`
3. See that `EXCLUDE` has no color styling

**Expected behavior**
I expect working keyword syntax in duckDB SQL (EXCLUDE, not EXCEPT) to have color styling.

**Additional context**
<img width="265" alt="image" src="https://user-images.githubusercontent.com/5587788/181121875-2f38b963-4128-47f9-9fb7-687743f1c5a8.png">

**Comment by mindspank** [comment]
fixed.
