### ISSUE TITLE
Axes ticks should be more appropriately spaced

### ISSUE THREAD

**Issue by djbarnwal** [rilldata/rill#695]
For a set of time ranges, generate an axis at a bunch of breakpoints. Each one of those breakpoints should look good & provide the info we need.

A PR should have - 
- a dev route that has a bunch of standalone data graphics with just an axis.
- each one will have a different width. Let’s have 3 breakpoints
- We cycle through a bunch of time ranges generating these graphs
- then we visually compare to see where the axis breaks down

**Comment by ericpgreen2** [comment]
Does this issue refer to the x-axis or to both x- and y- axes?

With multiple measures, I'm running into a situation where the y-axis ticks are confusing. The y=0 tick could be mistaken for the y=max tick in the graph below it. See especially the bottom graph here:
<img width="603" alt="image" src="https://user-images.githubusercontent.com/14206386/182723343-b8aa539b-48ac-44be-8b80-c6275529f5c7.png">
