### ISSUE TITLE
`Select` component makes it seem like an option is hovered when it isn't

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#743]
When I click on the time grain selector, see how the "weekly" option immediately appears to be hovered.

I'd expect the gray hover background to appear when my cursor first reaches the menu item.

![Kapture 2022-08-08 at 11 22 11](https://user-images.githubusercontent.com/14206386/183487144-a41478e9-2141-4e15-9afd-7f31254787d9.gif)

**Comment by mindspank** [comment]
Closing, not relevant anymore
