### ISSUE TITLE
Result set data table should be tighter

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#759]
Things to consider:
- Each column header takes up a lot of room due to the "data type" icon and the "pin column" icon. It leads to a lot of whitespace when the column's data is less wide than the column header.
- Font size in the data cells could possibly go down 1 size
- Less padding

If the compressed design feels way off when there's not much data, then consider a "comfy" and "compact" view toggle.

**Comment by bcolloran** [comment]
I very much agree with this. I think it resonates with the principal we've tried to articulate about how information density is very important for data tools, especially for tools that people are using for professional work. I'm not sure about changing the font size in particular, there might be a tradeoff there with legibility if it's too small but certainly something to experiment with. However I agree very much with the overall sentiment that it would be worth trying to get a little more information on the page for people who are trying to look through their data

**Comment by hamilton** [comment]
I'm not sure I 100% agree with most of this but we can definitely give it a shot after #739 lands and see how it feels
