### ISSUE TITLE
Missing data types in `duckdb-data-types.ts`

### ISSUE THREAD

**Issue by bcolloran** [rilldata/rill#782]
**Describe the bug**
there are a few data types described on the Dutch DB website that are not accounted for in our duck DB data type mapping code.

see
[`src\lib\duckdb-data-types.ts`](https://github.com/rilldata/rill-developer/blob/main/src/lib/duckdb-data-types.ts)
and
https://duckdb.org/docs/sql/data_types/overview

there are some data types that we don't handle and and that we probably shouldn't really work on for the foreseeable future, such as BLOB and the nested data types, but in that case perhaps we need to introduce a top level `invalid `concept (to go along with the concepts we already have of `categorical`, `numeric`, and `timestamp `) 

there are also a couple of other data types that are not included in the mapping that arguably we might wish to include, for example `UUID`, `enum`, `real`, and perhaps a couple others (I haven't done an exhaustive survey of all of the types, I just noticed this while looking at the duck DB docs— doing the exhaustive survey would be part of addressing this issue)

**Comment by jdgomeza** [comment]
Adding support for nested data types would be great. I have some parquet files with nested fields that I can only analyze if I transform them first. e.g., exploding the structs into flat column names `rootStruct.struct2.field1`

BTW. The dashboards look amazing!!!

**Comment by magorlick** [comment]
Thanks for swinging by to leave feedback @jdgomeza !  I encounter this all the time when I am exploring data - it is a common pattern. Today we are focused on supporting tabular data, but I have a note in our backlog and I will add your +1.
