### ISSUE TITLE
Dimension Table Enhancements

### ISSUE THREAD

**Issue by djbarnwal** [rilldata/rill#902]
- [ ] #905
- [x] #906
- [x] #907
- [x] #908
- [ ] Add svelte animations to the dimension table (on sort, select etc.)
- [x] #909
- [x] #910
- [x] #1017

**Comment by magorlick** [comment]
@djbarnwal , I am reviewing the related branch now and I want to help you focus this additional effort.


P0: Reference bars for each cell in the table is in scope, this was part of the mock we drew in Figma and a huge value add to get an impression of the data.
https://github.com/rilldata/rill-developer/issues/908

P2: Svelte animations on interaction are always fun and make the application feel polished and responsive.  Please timebox.
- [ ] Add svelte animations to the dimension table (on sort, select etc.)

P3



Not in Scope: These features are great ideas, but they are planned in other initiatives and have a larger scope than this table. Let's hold off for now and pivot to the work laid out as top priorities for the next release when you are done with the above.

https://github.com/rilldata/rill-developer/issues/909
https://github.com/rilldata/rill-developer/issues/910
https://github.com/rilldata/rill-developer/issues/906

**Comment by nishantmonu51** [comment]
Closing this as most of the work tracked under this ticket is done and rest needs further prioritization and scoping
