### ISSUE TITLE
Add link to Measures documentation on the Metrics Definition page

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#914]
Adding measures is a confusing part of the product. An empty "expression" cell is daunting. In the red box below, we should add a direct link to the Measures documentation: https://docs.rilldata.com/defining-metrics#measures

![image](https://user-images.githubusercontent.com/14206386/189728153-8f66bb2b-7ff6-4015-b618-7bc6372277da.png)

**Comment by mindspank** [comment]
Not relevant anymore, closing.
