### ISSUE TITLE
Support for TimescaleDB's hypertable

### ISSUE THREAD

**Issue by AshishKapoor** [rilldata/rill#941]
**Is your feature request related to a problem? Please describe.**
Does it support Postgres based TimescaleDB's [hypertable](https://docs.timescale.com/timescaledb/latest/how-to-guides/hypertables/about-hypertables/)? 

**Describe the solution you'd like**
Support for TimescaleDB's hypertable

**Additional context**
This should potentially help in time-series based data exploration.

**Comment by magorlick** [comment]
Thank you for the feature request!  We are considering integrating the duckDB connector to Postgres in our application.  

https://duckdb.org/2022/09/30/postgres-scanner.html

Would this help you get what you need? It sounds like you are interested in TimescaleDB, specifically? What features do you like about TimescaleDB that you are looking for here?

**Comment by AshishKapoor** [comment]
> Thank you for the feature request! We are considering integrating the duckDB connector to Postgres in our application.
> 
> https://duckdb.org/2022/09/30/postgres-scanner.html
> 
> Would this help you get what you need? It sounds like you are interested in TimescaleDB, specifically? What features do you like about TimescaleDB that you are looking for here?

Awesome! Sounds good to me!

I've been fiddling around with some sensors at home and TimescaleDB fits best for the use case.

**Comment by mindspank** [comment]
We support postgres since a while back that would allow you to talk to any postgres compliant databases. Let us know if you would run into any issues!
